### ISSUE TITLE
Cannot Find Dark Mode

### ISSUE THREAD

**Issue by slvrscoobie** [poblabs/weewx-belchertown#112]
Hey 
I had an older RC7 i think - and I just deleted everything in the skin folder, made a copy of graphs.conf and skin.conf, placed all new from development branch, and I broke everything. 
Seems like dark mode is throwing it? Can you help? 

```
Apr 30 18:50:27 raspberrypi weewx[2273]: reportengine: Report 'StandardReport' not enabled. Skipping.
Apr 30 18:50:27 raspberrypi weewx[2273]: reportengine: Report 'NeoReport' not enabled. Skipping.
Apr 30 18:50:27 raspberrypi weewx[2273]: reportengine: Running report 'Belchertown'
Apr 30 18:50:27 raspberrypi weewx[2273]: reportengine: Found configuration file /etc/weewx/skins/Belchertown/skin.conf for report 'Belchertown'
Apr 30 18:50:27 raspberrypi weewx[2273]: cheetahgenerator: using search list ['weewx.cheetahgenerator.Almanac', 'weewx.cheetahgenerator.Station', 'weewx.cheetahgenerator.Current', 'weewx.cheetahgenerator.Stats', 'weewx.cheetahgenerator.UnitInfo', 'weewx.cheetahgenerator.Extras', 'user.belchertown.getData']
Apr 30 18:50:27 raspberrypi weewx[2273]: manager: Daily summary version is 2.0
Apr 30 18:50:27 raspberrypi weewx[2273]: Belchertown Extension: version 1.0rc5
Apr 30 18:50:30 raspberrypi weewx[2273]: cheetahgenerator: Generate failed with exception '<class 'NameMapper.NotFound'>'
Apr 30 18:50:30 raspberrypi weewx[2273]: cheetahgenerator: **** Ignoring template /etc/weewx/skins/Belchertown/about/index.html.tmpl
Apr 30 18:50:30 raspberrypi weewx[2273]: cheetahgenerator: **** Reason: cannot find 'dark_mode' while searching for 'Extras.dark_mode'
Apr 30 18:50:30 raspberrypi weewx[2273]: ****  Traceback (most recent call last):
Apr 30 18:50:30 raspberrypi weewx[2273]: ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 332, in generate
Apr 30 18:50:30 raspberrypi weewx[2273]: ****      fd.write(str(compiled_template))
Apr 30 18:50:30 raspberrypi weewx[2273]: ****    File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 1005, in __str__
Apr 30 18:50:30 raspberrypi weewx[2273]: ****      rc = getattr(self, mainMethName)()
Apr 30 18:50:30 raspberrypi weewx[2273]: ****    File "_etc_weewx_skins_Belchertown_about_index_html_tmpl.py", line 92, in respond
Apr 30 18:50:30 raspberrypi weewx[2273]: ****    File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 1615, in _handleCheetahInclude
Apr 30 18:50:30 raspberrypi weewx[2273]: ****      self._CHEETAH__cheetahIncludes[_includeID].respond(trans)
Apr 30 18:50:30 raspberrypi weewx[2273]: ****    File "_etc_weewx_skins_Belchertown_header_html_tmpl.py", line 141, in respond
Apr 30 18:50:30 raspberrypi weewx[2273]: ****  NotFound: cannot find 'dark_mode' while searching for 'Extras.dark_mode'
Apr 30 18:50:30 raspberrypi weewx[2273]: cheetahgenerator: Generate failed with exception '<class 'NameMapper.NotFound'>'
Apr 30 18:50:30 raspberrypi weewx[2273]: cheetahgenerator: **** Ignoring template /etc/weewx/skins/Belchertown/graphs/index.html.tmpl
Apr 30 18:50:30 raspberrypi weewx[2273]: cheetahgenerator: **** Reason: cannot find 'dark_mode' while searching for 'Extras.dark_mode'
Apr 30 18:50:30 raspberrypi weewx[2273]: ****  Traceback (most recent call last):
Apr 30 18:50:30 raspberrypi weewx[2273]: ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 332, in generate
Apr 30 18:50:30 raspberrypi weewx[2273]: ****      fd.write(str(compiled_template))
Apr 30 18:50:30 raspberrypi weewx[2273]: ****    File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 1005, in __str__
Apr 30 18:50:30 raspberrypi weewx[2273]: ****      rc = getattr(self, mainMethName)()
Apr 30 18:50:30 raspberrypi weewx[2273]: ****    File "_etc_weewx_skins_Belchertown_graphs_index_html_tmpl.py", line 99, in respond
Apr 30 18:50:30 raspberrypi weewx[2273]: ****    File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 1615, in _handleCheetahInclude
Apr 30 18:50:30 raspberrypi weewx[2273]: ****      self._CHEETAH__cheetahIncludes[_includeID].respond(trans)
Apr 30 18:50:30 raspberrypi weewx[2273]: ****    File "_etc_weewx_skins_Belchertown_header_html_tmpl.py", line 141, in respond
Apr 30 18:50:30 raspberrypi weewx[2273]: ****  NotFound: cannot find 'dark_mode' while searching for 'Extras.dark_mode'
Apr 30 18:50:30 raspberrypi weewx[2273]: cheetahgenerator: Generate failed with exception '<class 'NameMapper.NotFound'>'
Apr 30 18:50:30 raspberrypi weewx[2273]: cheetahgenerator: **** Ignoring template /etc/weewx/skins/Belchertown/reports/index.html.tmpl
Apr 30 18:50:30 raspberrypi weewx[2273]: cheetahgenerator: **** Reason: cannot find 'dark_mode' while searching for 'Extras.dark_mode'
Apr 30 18:50:30 raspberrypi weewx[2273]: ****  Traceback (most recent call last):
Apr 30 18:50:30 raspberrypi weewx[2273]: ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 332, in generate
Apr 30 18:50:30 raspberrypi weewx[2273]: ****      fd.write(str(compiled_template))
Apr 30 18:50:30 raspberrypi weewx[2273]: ****    File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 1005, in __str__
Apr 30 18:50:30 raspberrypi weewx[2273]: ****      rc = getattr(self, mainMethName)()
Apr 30 18:50:30 raspberrypi weewx[2273]: ****    File "_etc_weewx_skins_Belchertown_reports_index_html_tmpl.py", line 113, in respond
Apr 30 18:50:30 raspberrypi weewx[2273]: ****    File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 1615, in _handleCheetahInclude
Apr 30 18:50:30 raspberrypi weewx[2273]: ****      self._CHEETAH__cheetahIncludes[_includeID].respond(trans)
Apr 30 18:50:30 raspberrypi weewx[2273]: ****    File "_etc_weewx_skins_Belchertown_header_html_tmpl.py", line 141, in respond
Apr 30 18:50:30 raspberrypi weewx[2273]: ****  NotFound: cannot find 'dark_mode' while searching for 'Extras.dark_mode'
Apr 30 18:50:31 raspberrypi weewx[2273]: cheetahgenerator: Generate failed with exception '<class 'NameMapper.NotFound'>'
Apr 30 18:50:31 raspberrypi weewx[2273]: cheetahgenerator: **** Ignoring template /etc/weewx/skins/Belchertown/records/index.html.tmpl
Apr 30 18:50:31 raspberrypi weewx[2273]: cheetahgenerator: **** Reason: cannot find 'dark_mode' while searching for 'Extras.dark_mode'
Apr 30 18:50:31 raspberrypi weewx[2273]: ****  Traceback (most recent call last):
Apr 30 18:50:31 raspberrypi weewx[2273]: ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 332, in generate
Apr 30 18:50:31 raspberrypi weewx[2273]: ****      fd.write(str(compiled_template))
Apr 30 18:50:31 raspberrypi weewx[2273]: ****    File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 1005, in __str__
Apr 30 18:50:31 raspberrypi weewx[2273]: ****      rc = getattr(self, mainMethName)()
Apr 30 18:50:31 raspberrypi weewx[2273]: ****    File "_etc_weewx_skins_Belchertown_records_index_html_tmpl.py", line 844, in respond
Apr 30 18:50:31 raspberrypi weewx[2273]: ****    File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 1615, in _handleCheetahInclude
Apr 30 18:50:31 raspberrypi weewx[2273]: ****      self._CHEETAH__cheetahIncludes[_includeID].respond(trans)
Apr 30 18:50:31 raspberrypi weewx[2273]: ****    File "_etc_weewx_skins_Belchertown_header_html_tmpl.py", line 141, in respond
Apr 30 18:50:31 raspberrypi weewx[2273]: ****  NotFound: cannot find 'dark_mode' while searching for 'Extras.dark_mode'
Apr 30 18:50:32 raspberrypi weewx[2273]: cheetahgenerator: Generate failed with exception '<class 'NameMapper.NotFound'>'
Apr 30 18:50:32 raspberrypi weewx[2273]: cheetahgenerator: **** Ignoring template /etc/weewx/skins/Belchertown/index.html.tmpl
Apr 30 18:50:32 raspberrypi weewx[2273]: cheetahgenerator: **** Reason: cannot find 'dark_mode' while searching for 'Extras.dark_mode'
Apr 30 18:50:32 raspberrypi weewx[2273]: ****  Traceback (most recent call last):
Apr 30 18:50:32 raspberrypi weewx[2273]: ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 332, in generate
Apr 30 18:50:32 raspberrypi weewx[2273]: ****      fd.write(str(compiled_template))
Apr 30 18:50:32 raspberrypi weewx[2273]: ****    File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 1005, in __str__
Apr 30 18:50:32 raspberrypi weewx[2273]: ****      rc = getattr(self, mainMethName)()
Apr 30 18:50:32 raspberrypi weewx[2273]: ****    File "_etc_weewx_skins_Belchertown_index_html_tmpl.py", line 454, in respond
Apr 30 18:50:32 raspberrypi weewx[2273]: ****    File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 1615, in _handleCheetahInclude
Apr 30 18:50:32 raspberrypi weewx[2273]: ****      self._CHEETAH__cheetahIncludes[_includeID].respond(trans)
Apr 30 18:50:32 raspberrypi weewx[2273]: ****    File "_etc_weewx_skins_Belchertown_header_html_tmpl.py", line 141, in respond
Apr 30 18:50:32 raspberrypi weewx[2273]: ****  NotFound: cannot find 'dark_mode' while searching for 'Extras.dark_mode'
Apr 30 18:50:34 raspberrypi weewx[2273]: sdr: MainThread: lines=['{"time" : "2019-04-30 22:50:29", "model" : "AmbientWeather-WH31E", "id" : 116, "channel" : 2, "battery" : "OK", "temperature_C" : 23.200, "humidity" : 43, "data" : "9800000000", "mic" : "CRC"}\n', '{"time" : "2019-04-30 22:50:29", "model" : "AmbientWeather-WH31E", "id" : 116, "channel" : 2, "battery" : "OK", "temperature_C" : 23.200, "humidity" : 43, "data" : "9800000000", "mic" : "CRC"}\n', '{"time" : "2019-04-30 22:50:30", "model" : "Fine Offset WH65B", "id" : 10, "temperature_C" : 16.600, "humidity" : 59, "wind_dir_deg" : 58, "wind_speed_ms" : 0.000, "gust_speed_ms" : 0.000, "rainfall_mm" : 451.612, "uv" : 62, "uvi" : 0, "light_lux" : 7858.000, "battery" : "OK", "mic" : "CRC"}\n']
Apr 30 18:50:34 raspberrypi weewx[2273]: sdr: MainThread: packet={'extraTemp2': 23.2, 'usUnits': 17, 'dateTime': 1556664629}
Apr 30 18:50:34 raspberrypi weewx[2273]: sdr: MainThread: ignoring duplicate packet {'extraTemp2': 23.2, 'usUnits': 17, 'dateTime': 1556664629}
Apr 30 18:50:34 raspberrypi weewx[2273]: sdr: MainThread: packet={'outTempBatteryStatus': 0, 'outHumidity': 59.0, 'light': 7858.0, 'UV': 0.0, 'dateTime': 1556664630, 'windDir': 58.0, 'outTemp': 16.6, 'windSpeed': 0.0, 'rain_total': 451.612, 'usUnits': 17}
Apr 30 18:50:35 raspberrypi weewx[2273]: cheetahgenerator: Generated 6 files for report Belchertown in 8.02 seconds
Apr 30 18:50:36 raspberrypi weewx[2273]: copygenerator: copied 32 files to /var/www/html/weewx/belchertown
Apr 30 18:50:36 raspberrypi weewx[2273]: manager: Daily summary version is 2.0
Apr 30 18:50:37 raspberrypi weewx[2273]: sdr: MainThread: lines=[]
```

**Comment by poblabs** [comment]
That's quite the log output, but it says you're using 1.0rc5. I don't think dark mode was until rc6 or 7? Try downloading everything again. 

Also, if your settings were copied to weewx.conf, then you can replace skin.conf with the new one in the download since it has had some big updates to it (new stuff added)

**Comment by poblabs** [comment]
Also, you need to restart weewx when you add/update/remove skins. So it could be referencing something old or accidentally deleted. 

I would, delete the Belchertown skin, go to user/bin, delete belchertown.py
Re-install the development branch fresh. Install that. 
Delete your HTML website for Belchertown
Restart weewx and let it re-generate everything

Give that a try

**Comment by slvrscoobie** [comment]
Thanks - thats basically what i did. So i dont need anything from the master branch? Just install Dev branch? I thought I had to overwrite the master with files from Dev

**Comment by slvrscoobie** [comment]
Where does the Assets folder go?

**Comment by poblabs** [comment]
Is your site public? I'm not sure what's been done anymore. Something's stuck. 

No - don't install master - that's the current production version which doesn't contain dark mode and has an old chart system that'll break the graphs.conf

If you've installed master, you'll want to make sure you delete any reference to highcharts. 

For good measure, follow the tips here: https://github.com/poblabs/weewx-belchertown/wiki/Upgrading-to-Belchertown-skin-1.0

Then restart weewx.

**Comment by poblabs** [comment]
The assets folder, and the images within, are for GitHub's use only for the wiki. They won't show up on yoru site and can be deleted

**Comment by slvrscoobie** [comment]
got it! ok, i didnt do anything, and boom theyre working again..

**Comment by poblabs** [comment]
Awesome!
