### ISSUE TITLE
String to float issue

### ISSUE THREAD

**Issue by Zimerhonzl** [poblabs/weewx-belchertown#20]
I recently had a temperature sensor go bad resulting in a NULL value in my database, but the rest of my station is working.  Unfortunately the current missing data breaks the skin and will not allow for any updates. I am using ver. 0.7.  (Line numbers below may not match up due to some custom coding)

Oct 22 09:42:22 gugelhupf weewx[1779]: cheetahgenerator: Generate failed with exception '<type 'exceptions.ValueError'>'
Oct 22 09:42:22 gugelhupf weewx[1779]: cheetahgenerator: **** Ignoring template /etc/weewx/skins/Belchertown/index.html.tmpl
Oct 22 09:42:22 gugelhupf weewx[1779]: cheetahgenerator: **** Reason: could not convert string to float: N/A
Oct 22 09:42:22 gugelhupf weewx[1779]: ****  Traceback (most recent call last):
Oct 22 09:42:22 gugelhupf weewx[1779]: ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 330, in generate
Oct 22 09:42:22 gugelhupf weewx[1779]: ****      print >> _file, compiled_template
Oct 22 09:42:22 gugelhupf weewx[1779]: ****    File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 1005, in __str__
Oct 22 09:42:22 gugelhupf weewx[1779]: ****      rc = getattr(self, mainMethName)()
Oct 22 09:42:22 gugelhupf weewx[1779]: ****    File "_etc_weewx_skins_Belchertown_index_html_tmpl.py", line 1336, in respond
Oct 22 09:42:22 gugelhupf weewx[1779]: ****  ValueError: could not convert string to float: N/A

**Comment by holyspidoo** [comment]
I have the same issue. Any luck?

**Comment by Zimerhonzl** [comment]
Sorry for delayed response.  I just had to deal with it until I replaced the sensor.

**Comment by Ysurac** [comment]
I had the same problem but I solved it by setting ```NONE = 0``` (instead of "N/A") in **[[StringFormats]]** section of ```skin.conf```.

**Comment by holyspidoo** [comment]
Thanks that solves it (NONE = 0 (instead of "N/A") in [[StringFormats]] section of skin.conf)

**Comment by Ysurac** [comment]
It was all the ISS for me.

**Comment by poblabs** [comment]
Thanks. I'm closing this for now. If anyone sees this again let me know so I can try to chase it down

**Comment by Zimerhonzl** [comment]
It was the temperature sensor reporting as NULL for me.

**Comment by poblabs** [comment]
I see. So if the db has NULL for outTemp then the skin would stop? I think I saw this issue with the rain column and had to implement a fix for it.

**Comment by poblabs** [comment]
Looks like there's a build-in weewx utility for this, but I'll see if I can do a workaround as well. 

Check out http://weewx.com/docs/utilities.htm#wee_database_utility_check_strings

**Comment by Zimerhonzl** [comment]
Thanks for checking it out.  The issue was with the live data update.  I
ran wee_database after I fixed my sensor for historical data, but while the
sensor was out all live data stopped and the skin would not update.  Might
be good to have an escape, similar to the rain fix for all data variables
in the future for the live data.  Although, this is likely a rare issue
when something malfunctions.

**Comment by poblabs** [comment]
Ah I see. My reference above was with the built-in outTemp reading, but you're indicating the live updates with MQTT?

**Comment by Zimerhonzl** [comment]
Didn't have my MQTT running at the time, may have to run a simulator to
test that one.  I encountered the issue during the WeeWX report process.
In the same cycle when the instrumentation is queried by the manager, the
Belchertown report would fail to generate when outTemp was NULL.  The
standard report skin still functioned and updated correctly.

**Comment by poblabs** [comment]
Hmm, ok. I'm not sure on the surface where I could sanitize for that. If it was with MQTT, then I know, but just a normal report generation - all that is internal to weewx and i just show those variables on the page.

Maybe I'll spin up another test instance and mark an outTemp value as NULL in the database and see if I can sanitize for it somewhere.

**Comment by Zimerhonzl** [comment]
Tom or Matt might have a suggestion since it's in the broader
functionality.  I'm curious if it affects other skins.

**Comment by poblabs** [comment]
Absolutely. I'm curious now, too. So I'll do a little digging then present it to them if it's their problem, and try to fix it if it's my problem :)

**Comment by Zimerhonzl** [comment]
Thanks Pat!

**Comment by poblabs** [comment]
So initial testing: 

If I set the outTemp to a proper NULL value, things are progressed fine and no problems generating the skin. 

![image](https://user-images.githubusercontent.com/3484775/48368541-05aa8b80-e682-11e8-86f8-5cfa0981912e.png)

If I set it to a NULL string (basically `""`) then it fails:

![image](https://user-images.githubusercontent.com/3484775/48368617-40acbf00-e682-11e8-807a-62e892fbd2cd.png)

```
root@weewxlab:~# service weewx restart; wee_reports; tail -f /var/log/syslog -n 50
Using configuration file /etc/weewx/weewx.conf
Generating for all time
Traceback (most recent call last):
  File "/usr/share/weewx/weewx/reportengine.py", line 239, in run
    obj.start()
  File "/usr/share/weewx/weewx/reportengine.py", line 273, in start
    self.run()
  File "/usr/share/weewx/weewx/imagegenerator.py", line 32, in run
    self.genImages(self.gen_ts)
  File "/usr/share/weewx/weewx/imagegenerator.py", line 235, in genImages
    image = plot.render()
  File "/usr/share/weewx/weeplot/genplot.py", line 191, in render
    self._calcYScaling()
  File "/usr/share/weewx/weeplot/genplot.py", line 496, in _calcYScaling
    self.yscale = weeplot.utilities.scale(ymin, ymax, self.yscale, nsteps=self.y_nticks)
  File "/usr/share/weewx/weeplot/utilities.py", line 72, in scale
    fmx = float(fmx)
ValueError: could not convert string to float:
```

So I think this comes down to a bad driver that you're using? 

The [weewx developer guide here](http://www.weewx.com/docs/devnotes.htm#Value_%22None%22
) says:
> Device drivers should be written to emit None if a data value is bad (perhaps because of a failed checksum). If the hardware simply doesn't support it, then the driver should not emit a value at all.

So if you had a failed sensor, the driver should have seen the bad data and then submitted a None to the database which (I'm pretty certain) would be a NULL value (not a NULL string), and would get ignored on report generation. 

This is a little outside the scope of this extension, but I'm curious - Which driver are you using?

**Comment by Zimerhonzl** [comment]
I am using ObserverIP, which is a bit of a workaround in itself it seems.
Glad you were able to catch the NULL vs NULL string.  I'll reach out on the
google-group about the issue in the driver.

**Comment by Zimerhonzl** [comment]
No, I'm using the one with update from Matthew Wall, circa 2017.

**Comment by poblabs** [comment]
Ah, I see. Matthew should have that driver buttoned up pretty well, but might be worth a double check on it.

**Comment by poblabs** [comment]
FYI - I finally got my hands on a database where the string to float issue was happening with, and i've resolved it in https://github.com/poblabs/weewx-belchertown/commit/832a73ee87fc61985edf11580495e58fc96b706e

I know you're all fixed - but this will be a permanent fix without changing `NONE = 0` in 0.8.1 when it's released in a few days.
