### ISSUE TITLE
WeeWX version: 4.0.0b6 and Belchertown Skin Version: 1.1b8

### ISSUE THREAD

**Issue by salinois** [poblabs/weewx-belchertown#241]
hello PAT

I am trying your skin with weewx4b6, installation ok; no errors
but I have many errors

Jan  3 18:40:22 raspberrypi weewx[8593] INFO weewx.imagegenerator: Generated 4 images for MobileReport in 0.52 seconds
Jan  3 18:40:22 raspberrypi weewx[8593] INFO weewx.reportengine: Copied 0 files to /var/www/html/weewx/mobile
Jan  3 18:40:23 raspberrypi weewx[8593] ERROR weewx.reportengine: reportengine: Caught unrecoverable exception in generator 'weewx.cheetahgenerator.CheetahGenerator'
Jan  3 18:40:23 raspberrypi weewx[8593] ERROR weewx.reportengine:         ****  invalid syntax (belchertown_highchartsSearchX.py, line 41)
Jan  3 18:40:23 raspberrypi weewx[8593] ERROR weewx.reportengine:         ****  Traceback (most recent call last):
Jan  3 18:40:23 raspberrypi weewx[8593] ERROR weewx.reportengine:         ****    File "/home/weewx/bin/weewx/reportengine.py", line 202, in run
Jan  3 18:40:23 raspberrypi weewx[8593] ERROR weewx.reportengine:         ****      obj.start()
Jan  3 18:40:23 raspberrypi weewx[8593] ERROR weewx.reportengine:         ****    File "/home/weewx/bin/weewx/reportengine.py", line 285, in start
Jan  3 18:40:23 raspberrypi weewx[8593] ERROR weewx.reportengine:         ****      self.run()
Jan  3 18:40:23 raspberrypi weewx[8593] ERROR weewx.reportengine:         ****    File "/home/weewx/bin/weewx/cheetahgenerator.py", line 147, in run
Jan  3 18:40:23 raspberrypi weewx[8593] ERROR weewx.reportengine:         ****      self.initExtensions(gen_dict[section_name])
Jan  3 18:40:23 raspberrypi weewx[8593] ERROR weewx.reportengine:         ****    File "/home/weewx/bin/weewx/cheetahgenerator.py", line 189, in initExtensions
Jan  3 18:40:23 raspberrypi weewx[8593] ERROR weewx.reportengine:         ****      class_ = weeutil.weeutil.get_object(x)
Jan  3 18:40:23 raspberrypi weewx[8593] ERROR weewx.reportengine:         ****    File "/home/weewx/bin/weeutil/weeutil.py", line 1093, in get_object
Jan  3 18:40:23 raspberrypi weewx[8593] ERROR weewx.reportengine:         ****      mod = __import__(module)
Jan  3 18:40:23 raspberrypi weewx[8593] ERROR weewx.reportengine:         ****    File "/home/weewx/bin/user/belchertown_highchartsSearchX.py", line 41
Jan  3 18:40:23 raspberrypi weewx[8593] ERROR weewx.reportengine:         ****      except Exception, e:
Jan  3 18:40:23 raspberrypi weewx[8593] ERROR weewx.reportengine:         ****                      ^
Jan  3 18:40:23 raspberrypi weewx[8593] ERROR weewx.reportengine:         ****  SyntaxError: invalid syntax
Jan  3 18:40:23 raspberrypi weewx[8593] ERROR weewx.reportengine:         ****  Generator terminated
Jan  3 18:40:23 raspberrypi weewx[8593] INFO weewx.reportengine: Copied 0 files to /var/www/html/weewx/belchertown
Jan  3 18:40:23 raspberrypi weewx[8593] ERROR user.belchertown: Update Checker: Error downloading GitHub Version data. The error is: the JSON object must be str, not 'bytes'
Jan  3 18:40:23 raspberrypi weewx[8593] ERROR user.belchertown: Update Checker: Unable to open /var/www/html/weewx/belchertown/json/github_version.json. Reason: [Errno 2] Aucun fichier ou dossier de ce type: '/var/www/html/weewx/belchertown/json/github_version.json'
Jan  3 18:40:24 raspberrypi weewx[8593] ERROR user.belchertown: Update Checker: Error downloading GitHub Version data. The error is: the JSON object must be str, not 'bytes'
Jan  3 18:40:24 raspberrypi weewx[8593] ERROR user.belchertown: Update Checker: Unable to open /var/www/html/weewx/belchertown/json/github_version.json. Reason: [Errno 2] Aucun fichier ou dossier de ce type: '/var/www/html/weewx/belchertown/json/github_version.json'
Jan  3 18:40:26 raspberrypi weewx[8593] ERROR user.belchertown: Update Checker: Error downloading GitHub Version data. The error is: the JSON object must be str, not 'bytes'
Jan  3 18:40:26 raspberrypi weewx[8593] ERROR user.belchertown: Update Checker: Unable to open /var/www/html/weewx/belchertown/json/github_version.json. Reason: [Errno 2] Aucun fichier ou dossier de ce type: '/var/www/html/weewx/belchertown/json/github_version.json'
Jan  3 18:40:26 raspberrypi weewx[8593] ERROR user.belchertown: Update Checker: Error downloading GitHub Version data. The error is: the JSON object must be str, not 'bytes'
Jan  3 18:40:26 raspberrypi weewx[8593] ERROR user.belchertown: Update Checker: Unable to open /var/www/html/weewx/belchertown/json/github_version.json. Reason: [Errno 2] Aucun fichier ou dossier de ce type: '/var/www/html/weewx/belchertown/json/github_version.json'
Jan  3 18:40:27 raspberrypi weewx[8593] ERROR user.belchertown: Update Checker: Error downloading GitHub Version data. The error is: the JSON object must be str, not 'bytes'
Jan  3 18:40:27 raspberrypi weewx[8593] ERROR user.belchertown: Update Checker: Unable to open /var/www/html/weewx/belchertown/json/github_version.json. Reason: [Errno 2] Aucun fichier ou dossier de ce type: '/var/www/html/weewx/belchertown/json/github_version.json'
Jan  3 18:40:28 raspberrypi weewx[8593] ERROR user.belchertown: Update Checker: Error downloading GitHub Version data. The error is: the JSON object must be str, not 'bytes'
Jan  3 18:40:28 raspberrypi weewx[8593] ERROR user.belchertown: Update Checker: Unable to open /var/www/html/weewx/belchertown/json/github_version.json. Reason: [Errno 2] Aucun fichier ou dossier de ce type: '/var/www/html/weewx/belchertown/json/github_version.json'
Jan  3 18:40:28 raspberrypi weewx[8593] ERROR user.belchertown: Update Checker: Error downloading GitHub Version data. The error is: the JSON object must be str, not 'bytes'
Jan  3 18:40:28 raspberrypi weewx[8593] ERROR user.belchertown: Update Checker: Unable to open /var/www/html/weewx/belchertown/json/github_version.json. Reason: [Errno 2] Aucun fichier ou dossier de ce type: '/var/www/html/weewx/belchertown/json/github_version.json'
Jan  3 18:40:29 raspberrypi weewx[8593] ERROR user.belchertown: Update Checker: Error downloading GitHub Version data. The error is: the JSON object must be str, not 'bytes'
Jan  3 18:40:29 raspberrypi weewx[8593] ERROR user.belchertown: Update Checker: Unable to open /var/www/html/weewx/belchertown/json/github_version.json. Reason: [Errno 2] Aucun fichier ou dossier de ce type: '/var/www/html/weewx/belchertown/json/github_version.json'
Jan  3 18:40:29 raspberrypi weewx[8593] ERROR user.belchertown: Update Checker: Error downloading GitHub Version data. The error is: the JSON object must be str, not 'bytes'
Jan  3 18:40:29 raspberrypi weewx[8593] ERROR user.belchertown: Update Checker: Unable to open /var/www/html/weewx/belchertown/json/github_version.json. Reason: [Errno 2] Aucun fichier ou dossier de ce type: '/var/www/html/weewx/belchertown/json/github_version.json'
Jan  3 18:40:30 raspberrypi weewx[8593] ERROR user.belchertown: Update Checker: Error downloading GitHub Version data. The error is: the JSON object must be str, not 'bytes'
Jan  3 18:40:30 raspberrypi weewx[8593] ERROR user.belchertown: Update Checker: Unable to open /var/www/html/weewx/belchertown/json/github_version.json. Reason: [Errno 2] Aucun fichier ou dossier de ce type: '/var/www/html/weewx/belchertown/json/github_version.json'
Jan  3 18:40:30 raspberrypi weewx[8593] ERROR user.belchertown: Update Checker: Error downloading GitHub Version data. The error is: the JSON object must be str, not 'bytes'
Jan  3 18:40:30 raspberrypi weewx[8593] ERROR user.belchertown: Update Checker: Unable to open /var/www/html/weewx/belchertown/json/github_version.json. Reason: [Errno 2] Aucun fichier ou dossier de ce type: '/var/www/html/weewx/belchertown/json/github_version.json'
Jan  3 18:40:30 raspberrypi weewx[8593] INFO weewx.cheetahgenerator: Generated 11 files for report Belchertown in 7.22 seconds
Jan  3 18:40:30 raspberrypi weewx[8593] INFO weewx.reportengine: Copied 2 files to /var/www/html/weewx/belchertown

any idea

patrick

**Comment by salinois** [comment]
the skin works fine also !!!!!
I have forgotten somethings with installation ?

patrick
