### ISSUE TITLE
weewx 4.0.0 generate failed with exception

### ISSUE THREAD

**Issue by elcanux** [poblabs/weewx-belchertown#278]
Hi,

I have updated weewx to 4.0.0 today and now i have an exception witch theme: 
```
May  6 19:51:07 server weewx[8713] INFO __main__: Initializing weewx version 4.0.0
May  6 19:51:07 server weewx[8713] INFO __main__: Using Python 2.7.13 (default, Sep 26 2018, 18:42:22) #012[GCC 6.3.0 20170516]
May  6 19:51:07 server weewx[8713] INFO __main__: Platform Linux-4.14.165+-armv7l-with-debian-9.12
May  6 19:51:07 server weewx[8713] INFO __main__: Locale is 'fr_FR.UTF-8'
May  6 19:51:07 server weewx[8713] INFO __main__: PID file is /var/run/weewx.pid
```

```
May  6 19:55:18 server weewx[8717] INFO user.belchertown: version 1.2b3
May  6 19:55:19 server weewx[8717] ERROR weewx.cheetahgenerator: Generate failed with exception '<type 'exceptions.UnicodeDecodeError'>'
May  6 19:55:19 server weewx[8717] ERROR weewx.cheetahgenerator: **** Ignoring template /etc/weewx/skins/Belchertown/about/index.html.tmpl
May  6 19:55:19 server weewx[8717] ERROR weewx.cheetahgenerator: **** Reason: 'ascii' codec can't decode byte 0xc3 in position 2489: ordinal not in range(128)
May  6 19:55:19 server weewx[8717] ERROR weewx.cheetahgenerator: ****  Traceback (most recent call last):
May  6 19:55:19 server weewx[8717] ERROR weewx.cheetahgenerator: ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 322, in generate
May  6 19:55:19 server weewx[8717] ERROR weewx.cheetahgenerator: ****      unicode_string = compiled_template.respond()
May  6 19:55:19 server weewx[8717] ERROR weewx.cheetahgenerator: ****    File "_etc_weewx_skins_Belchertown_about_index_html_tmpl.py", line 103, in respond
May  6 19:55:19 server weewx[8717] ERROR weewx.cheetahgenerator: ****    File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 1597, in _handleCheetahInclude
May  6 19:55:19 server weewx[8717] ERROR weewx.cheetahgenerator: ****      nestedTemplateClass = compiler.compile(source=source, file=file)
May  6 19:55:19 server weewx[8717] ERROR weewx.cheetahgenerator: ****    File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 740, in compile
May  6 19:55:19 server weewx[8717] ERROR weewx.cheetahgenerator: ****      settings=(compilerSettings or {}))
May  6 19:55:19 server weewx[8717] ERROR weewx.cheetahgenerator: ****    File "/usr/lib/python2.7/dist-packages/Cheetah/Compiler.py", line 1579, in __init__
May  6 19:55:19 server weewx[8717] ERROR weewx.cheetahgenerator: ****      source = unicode(source)
May  6 19:55:19 server weewx[8717] ERROR weewx.cheetahgenerator: ****  UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2489: ordinal not in range(128)
May  6 19:55:23 server weewx[8717] INFO weewx.cheetahgenerator: Generated 10 files for report Belchertown in 5.68 seconds
```

do you have an idea ?

**Comment by poblabs** [comment]
Add this to the top of your about.inc

`#encoding UTF-8`

**Comment by elcanux** [comment]
It works, Thanks !
