### ISSUE TITLE
Exception in generator 'weewx.cheetahgenerator.CheetahGenerator'

### ISSUE THREAD

**Issue by kalju** [poblabs/weewx-belchertown#292]
After update to Weewx 4.1.1 (python 3) and Belchertown 1.1 skin during the report generation receiving following error: 

```
Jun  1 17:45:19 pi weewx[22082] INFO user.belchertown: version 1.1
Jun  1 17:45:19 pi weewx[22082] ERROR weewx.reportengine: Caught unrecoverable exception in generator 'weewx.cheetahgenerator.CheetahGenerator'
Jun  1 17:45:19 pi weewx[22082] ERROR weewx.reportengine:         ****  'check_for_updates'
Jun  1 17:45:19 pi weewx[22082] ERROR weewx.reportengine:         ****  Traceback (most recent call last):
Jun  1 17:45:19 pi weewx[22082] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 197, in run
Jun  1 17:45:19 pi weewx[22082] ERROR weewx.reportengine:         ****      obj.start()
Jun  1 17:45:19 pi weewx[22082] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 280, in start
Jun  1 17:45:19 pi weewx[22082] ERROR weewx.reportengine:         ****      self.run()
Jun  1 17:45:19 pi weewx[22082] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 150, in run
Jun  1 17:45:19 pi weewx[22082] ERROR weewx.reportengine:         ****      ngen = self.generate(gen_dict[section_name], self.gen_ts)
Jun  1 17:45:19 pi weewx[22082] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 220, in generate
Jun  1 17:45:19 pi weewx[22082] ERROR weewx.reportengine:         ****      ngen += self.generate(section[subsection], gen_ts)
Jun  1 17:45:19 pi weewx[22082] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 220, in generate
Jun  1 17:45:19 pi weewx[22082] ERROR weewx.reportengine:         ****      ngen += self.generate(section[subsection], gen_ts)
Jun  1 17:45:19 pi weewx[22082] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 309, in generate
Jun  1 17:45:19 pi weewx[22082] ERROR weewx.reportengine:         ****      default_binding)
Jun  1 17:45:19 pi weewx[22082] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 376, in _getSearchList
Jun  1 17:45:19 pi weewx[22082] ERROR weewx.reportengine:         ****      searchList += obj.get_extension_list(timespan, db_lookup)
Jun  1 17:45:19 pi weewx[22082] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/user/belchertown.py", line 737, in get_extension_list
Jun  1 17:45:19 pi weewx[22082] ERROR weewx.reportengine:         ****      if self.generator.skin_dict['Extras']['check_for_updates'] == "1":
Jun  1 17:45:19 pi weewx[22082] ERROR weewx.reportengine:         ****    File "/usr/lib/python3/dist-packages/configobj.py", line 554, in __getitem__
Jun  1 17:45:19 pi weewx[22082] ERROR weewx.reportengine:         ****      val = dict.__getitem__(self, key)
Jun  1 17:45:19 pi weewx[22082] ERROR weewx.reportengine:         ****  KeyError: 'check_for_updates'
Jun  1 17:45:19 pi weewx[22082] ERROR weewx.reportengine:         ****  Generator terminated
```

**Comment by poblabs** [comment]
Did you update your skin.conf too? Looks like your missing some options from that file.

**Comment by kalju** [comment]
wow, quick. will check

**Comment by poblabs** [comment]
I would reinstall the skin.conf file with the newest one, then restart weewx. Let me know how that goes

**Comment by kalju** [comment]
Took me some time, skin.con heavily localized. But everything OK now.
Thanks for quick suggestion and help!

**Comment by poblabs** [comment]
Sounds good! To prevent this in future, you should copy your skin.conf settings to weewx.conf - that way skin.conf can get upgraded without much work. 

Check this out for help:

https://github.com/poblabs/weewx-belchertown#skin-options

https://github.com/poblabs/weewx-belchertown#translating-the-skin

https://github.com/poblabs/weewx-belchertown#frequently-asked-questions

**Comment by kalju** [comment]
Thanks!
I need to take time to do that at last. Enough postponing :-)

Best,

Kalju

---------------------------------------------------
Get closer than ever to your customers. 
So close that you tell them what they need well before they realize it themselves. 
												-- Steve Jobs --
