### ISSUE TITLE
Forecast problem with version 1.2b6

### ISSUE THREAD

**Issue by swiggers** [poblabs/weewx-belchertown#323]
Hi,

I have the following error when I run wee_reports:

> Traceback (most recent call last):
>   File "/usr/share/weewx/weewx/reportengine.py", line 197, in run
>     obj.start()
>   File "/usr/share/weewx/weewx/reportengine.py", line 280, in start
>     self.run()
>   File "/usr/share/weewx/weewx/cheetahgenerator.py", line 150, in run
>     ngen = self.generate(gen_dict[section_name], self.gen_ts)
>   File "/usr/share/weewx/weewx/cheetahgenerator.py", line 220, in generate
>     ngen += self.generate(section[subsection], gen_ts)
>   File "/usr/share/weewx/weewx/cheetahgenerator.py", line 220, in generate
>     ngen += self.generate(section[subsection], gen_ts)
>   File "/usr/share/weewx/weewx/cheetahgenerator.py", line 309, in generate
>     default_binding)
>   File "/usr/share/weewx/weewx/cheetahgenerator.py", line 376, in _getSearchList
>     searchList += obj.get_extension_list(timespan, db_lookup)
>   File "/usr/share/weewx/user/belchertown.py", line 880, in get_extension_list
>     current_obs_summary = aeris_coded_weather( data["current"][0]["response"]["ob"]["weatherPrimaryCoded"] )
> TypeError: list indices must be integers or slices, not str

I have no idea where the error come from.

**Comment by swiggers** [comment]
I solved the problem: Its nessesary to link de API wtih https://www.pwsweather.com/
