### ISSUE TITLE
station_observations not working as expected

### ISSUE THREAD

**Issue by weswitt** [poblabs/weewx-belchertown#327]
i'm seeing 2 issues running the current version of the skin and weewx.

1) if i delete the station_observations line from skins/Belchertown/skin.conf and add it to weewx.conf in the Belchertown Extras section then report generation fails:

Generating for all time
Traceback (most recent call last):
  File "/home/weewx/bin/weewx/reportengine.py", line 197, in run
    obj.start()
  File "/home/weewx/bin/weewx/reportengine.py", line 280, in start
    self.run()
  File "/home/weewx/bin/weewx/cheetahgenerator.py", line 150, in run
    ngen = self.generate(gen_dict[section_name], self.gen_ts)
  File "/home/weewx/bin/weewx/cheetahgenerator.py", line 220, in generate
    ngen += self.generate(section[subsection], gen_ts)
  File "/home/weewx/bin/weewx/cheetahgenerator.py", line 220, in generate
    ngen += self.generate(section[subsection], gen_ts)
  File "/home/weewx/bin/weewx/cheetahgenerator.py", line 308, in generate
    searchList = self._getSearchList(encoding, timespan,
  File "/home/weewx/bin/weewx/cheetahgenerator.py", line 376, in _getSearchList
    searchList += obj.get_extension_list(timespan, db_lookup)
  File "/home/weewx/bin/user/belchertown.py", line 804, in get_extension_list
    station_observations = self.generator.skin_dict['Extras']['station_observations']
  File "/usr/lib/python3/dist-packages/configobj.py", line 554, in __getitem__
    val = dict.__getitem__(self, key)
KeyError: 'station_observations'

2) adding "inTemp" and "extraTemp1" to station_observations does not cause those observations to be generated on the page

**Comment by poblabs** [comment]
For item 1, do not delete it. It needs to be there. Weewx.conf will
override anything In skin.conf but the entry still needs to exist.

Item 2 I'll have to research when I can

**Comment by weswitt** [comment]
ok, in my testing it appears that the report generation does not pay attention to the station_observations at all. i changed it to:

station_observations = "barometer"

and then restarted weewx and ran wee_reports.

the page did not change. i still have temperature, wind, rain & barometer.

am i doing something wrong?

**Comment by poblabs** [comment]
Do you have mqtt enabled?

**Comment by poblabs** [comment]
Also what errors are in your syslog? If nothing changed then there's an
error somewhere..

**Comment by weswitt** [comment]
this was caused by deleting lines from the skin.conf
