### ISSUE TITLE
Updated PI to buster now getting this error

### ISSUE THREAD

**Issue by sgrayban** [poblabs/weewx-belchertown#351]
Traceback (most recent call last):
  File "/usr/share/weewx/weewx/reportengine.py", line 197, in run
    obj.start()
  File "/usr/share/weewx/weewx/reportengine.py", line 280, in start
    self.run()
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 150, in run
    ngen = self.generate(gen_dict[section_name], self.gen_ts)
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 220, in generate
    ngen += self.generate(section[subsection], gen_ts)
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 220, in generate
    ngen += self.generate(section[subsection], gen_ts)
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 309, in generate
    default_binding)
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 376, in _getSearchList
    searchList += obj.get_extension_list(timespan, db_lookup)
  File "/usr/share/weewx/user/belchertown.py", line 880, in get_extension_list
    current_obs_summary = aeris_coded_weather( data["current"][0]["response"]["ob"]["weatherPrimaryCoded"] )
TypeError: list indices must be integers or slices, not str

**Comment by poblabs** [comment]
I don't think this is related to Buster. Looks like you may have an old forecast.json file, or a mismatch config between Aeris and DarkSky. You could delete the forecast.json from your html folder, run wee_reports and try again. Make sure your files are all updated - especially skin.conf, and that you don't have both weather services enabled,

**Comment by sgrayban** [comment]
Got that sorted out but now I can't get interceptor to sniff now. All I get is user.interceptor: empty queue even though when I run it manually it gets the data. I have searched google and many posts but not 1 single fix yet. Very frustrated now.

**Comment by sgrayban** [comment]
Well now mqtt is reporting current weather but the pages arent getting generated with the last know weather data... EG; temp says its 32F
