### ISSUE TITLE
Errors after migration to MySQL

### ISSUE THREAD

**Issue by magnum61** [poblabs/weewx-belchertown#377]
I've migrated my WeeWX installation successfully to MySQL.

But whenever the Belchertown skin is used, i am getting errors reported in syslog. Beside that the system runs fine.
How do i get this fixed?

Errors in Syslog below. These are shown on every run of the reporting engine:

```
Aug 31 18:05:35 WeeWX weewx[18750] ERROR weewx.reportengine: Caught unrecoverable exception in generator 'user.belchertown.HighchartsJsonGenerator'
Aug 31 18:05:35 WeeWX weewx[18750] ERROR weewx.reportengine: **** Error trying to use database binding wx_binding to graph observation maxSolarRad. Error was: maxSolarRad.
Aug 31 18:05:35 WeeWX weewx[18750] ERROR weewx.reportengine: **** Traceback (most recent call last):
Aug 31 18:05:35 WeeWX weewx[18750] ERROR weewx.reportengine: **** File "/usr/share/weewx/user/belchertown.py", line 2325, in get_observation_data
Aug 31 18:05:35 WeeWX weewx[18750] ERROR weewx.reportengine: **** (time_start_vt, time_stop_vt, obs_vt) = archive.getSqlVectors(TimeSpan(start_ts, end_ts), obs_lookup, aggregate_type, aggregate_interval)
Aug 31 18:05:35 WeeWX weewx[18750] ERROR weewx.reportengine: **** File "/usr/share/weewx/weewx/manager.py", line 452, in getSqlVectors
Aug 31 18:05:35 WeeWX weewx[18750] ERROR weewx.reportengine: **** aggregate_type, aggregate_interval)
Aug 31 18:05:35 WeeWX weewx[18750] ERROR weewx.reportengine: **** File "/usr/share/weewx/weewx/xtypes.py", line 91, in get_series
Aug 31 18:05:35 WeeWX weewx[18750] ERROR weewx.reportengine: **** raise weewx.UnknownType(obs_type)
Aug 31 18:05:35 WeeWX weewx[18750] ERROR weewx.reportengine: **** weewx.UnknownType: maxSolarRad
Aug 31 18:05:35 WeeWX weewx[18750] ERROR weewx.reportengine: ****
Aug 31 18:05:35 WeeWX weewx[18750] ERROR weewx.reportengine: **** During handling of the above exception, another exception occurred:
Aug 31 18:05:35 WeeWX weewx[18750] ERROR weewx.reportengine: ****
Aug 31 18:05:35 WeeWX weewx[18750] ERROR weewx.reportengine: **** Traceback (most recent call last):
Aug 31 18:05:35 WeeWX weewx[18750] ERROR weewx.reportengine: **** File "/usr/share/weewx/weewx/reportengine.py", line 197, in run
Aug 31 18:05:35 WeeWX weewx[18750] ERROR weewx.reportengine: **** obj.start()
Aug 31 18:05:35 WeeWX weewx[18750] ERROR weewx.reportengine: **** File "/usr/share/weewx/weewx/reportengine.py", line 280, in start
Aug 31 18:05:35 WeeWX weewx[18750] ERROR weewx.reportengine: **** self.run()
Aug 31 18:05:35 WeeWX weewx[18750] ERROR weewx.reportengine: **** File "/usr/share/weewx/user/belchertown.py", line 1823, in run
Aug 31 18:05:35 WeeWX weewx[18750] ERROR weewx.reportengine: **** series_data = self.get_observation_data(binding, archive, observation_type, minstamp, maxstamp, aggregate_type, aggregate_interval, time_length, xAxis_groupby, xAxis_categories, mirrored_value, weatherRange_obs_lookup, wind_rose_color)
Aug 31 18:05:35 WeeWX weewx[18750] ERROR weewx.reportengine: **** File "/usr/share/weewx/user/belchertown.py", line 2327, in get_observation_data
Aug 31 18:05:35 WeeWX weewx[18750] ERROR weewx.reportengine: **** raise Warning( "Error trying to use database binding %s to graph observation %s. Error was: %s." % (binding, obs_lookup, e) )
Aug 31 18:05:35 WeeWX weewx[18750] ERROR weewx.reportengine: **** Warning: Error trying to use database binding wx_binding to graph observation maxSolarRad. Error was: maxSolarRad.
Aug 31 18:05:35 WeeWX weewx[18750] ERROR weewx.reportengine: **** Generator terminated
```

**Comment by poblabs** [comment]
Your mysql database is missing the `maxSolarRad` column. You can either use the weewx v4 schema (default on new weewx 4 installs), or add it [using these instructions](https://github.com/poblabs/weewx-belchertown/wiki/Adding-a-new-observation-type-to-the-WeeWX-database)

**Comment by magnum61** [comment]
Thank you for your fast response.

I am using the latest WeeWX version (4.1.x), so the question is why it is missing.

**Comment by poblabs** [comment]
Good question. I think in weewx.conf, you want your [DataBindings] [[wx_binding]] schema = schemas.wview_extended.schema when you create the database for the first time. If that doesn't work, then I'd ask over on the [weewx user forums](https://groups.google.com/forum/#!forum/weewx-user).

**Comment by magnum61** [comment]
This is the part in my weewx.conf, so it looks it is already there:

```
    [[wx_binding]]
        # The database must match one of the sections in [Databases].
        # This is likely to be the only option you would want to change.
        database = archive_mysql
        # The name of the table within the database
        table_name = archive
        # The manager handles aggregation of data for historical summaries
        manager = weewx.manager.DaySummaryManager
        # The schema defines the structure of the database.
        # It is *only* used when the database is created.
        schema = schemas.wview_extended.schema
```

**Comment by poblabs** [comment]
Strange, that should have done it as far as I remember. Sorry I can't help more.

**Comment by magnum61** [comment]
I think i have found the error.
I was using the wee_database utility as documented on the migration section in weewx-Wiki:
https://github.com/weewx/weewx/wiki/Transfer-from-sqlite-to-MySQL

There the dest_binding shows a wrong line:
`schema = schemas.wview.schema`

With this the extended data is missing.
I was running it again, this time with this line:
`schema = schemas.wview_**extended**.schema
`
Now it is working without errors.
Just in case someone is asking again :)
