### ISSUE TITLE
Problem introducing DarkSky in weewx.conf

### ISSUE THREAD

**Issue by spanishhighs** [poblabs/weewx-belchertown#39]
I have a site that works perfectly well with this wonderful skin. It pulls down station info using WeatherFlowUDP and then uploads via FTP to my server. All looks ok until I introduce the following DarkSky details into weewx.conf. 

```
forecast_enabled = 1
darksky_secret_key = "secret_number_alpha_key_from_darkskyapi"
```

I then get a Generator Terminated warning in Syslog due to
`"UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 68: ordinal not in range(128)"`

I am using the latest /usr/share/weewx/user/belchertown.py and have desktop ubuntu 18.04. 

I am not a developer and thus is now a bit beyond me. Can anyone help?

Site at https://www.spanishhighs.co.uk/test/belchertown/

Thanks
Richard

Full Syslog details:

```
Jan  8 17:00:19 richard-pc weewx[30139]: weatherflowudp: MainThread: Listening for UDP broadcasts to IP address 0.0.0.0 on port 50222, with timeout 90 and share_socket False...
Jan  8 17:00:19 richard-pc weewx[30139]: cheetahgenerator: Generated 14 files for report StandardReport in 0.45 seconds
Jan  8 17:00:19 richard-pc weewx[30139]: imagegenerator: Generated 24 images for StandardReport in 0.30 seconds
Jan  8 17:00:19 richard-pc weewx[30139]: copygenerator: copied 9 files to /var/www/html/weewx
Jan  8 17:00:20 richard-pc weewx[30139]: cheetahgenerator: Generated 4 files for report Highcharts_Belchertown in 0.53 seconds
Jan  8 17:00:20 richard-pc weewx[30139]: copygenerator: copied 0 files to /var/www/html/weewx/belchertown
Jan  8 17:00:20 richard-pc weewx[30139]: Belchertown Extension: version 0.8.2
Jan  8 17:00:21 richard-pc weewx[30139]: Belchertown Extension: New forecast file downloaded to /var/www/html/weewx/belchertown/json/darksky_forecast.json
Jan  8 17:00:21 richard-pc weewx[30139]: reportengine: Caught unrecoverable exception in generator weewx.cheetahgenerator.CheetahGenerator
Jan  8 17:00:21 richard-pc weewx[30139]:         ****  'ascii' codec can't decode byte 0xc3 in position 68: ordinal not in range(128)
Jan  8 17:00:21 richard-pc weewx[30139]:         ****  Traceback (most recent call last):
Jan  8 17:00:21 richard-pc weewx[30139]:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 239, in run
Jan  8 17:00:21 richard-pc weewx[30139]:         ****      obj.start()
Jan  8 17:00:21 richard-pc weewx[30139]:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 273, in start
Jan  8 17:00:21 richard-pc weewx[30139]:         ****      self.run()
Jan  8 17:00:21 richard-pc weewx[30139]:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 158, in run
Jan  8 17:00:21 richard-pc weewx[30139]:         ****      ngen = self.generate(gen_dict[section_name], self.gen_ts)
Jan  8 17:00:21 richard-pc weewx[30139]:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 232, in generate
Jan  8 17:00:21 richard-pc weewx[30139]:         ****      ngen += self.generate(section[subsection], gen_ts)
Jan  8 17:00:21 richard-pc weewx[30139]:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 232, in generate
Jan  8 17:00:21 richard-pc weewx[30139]:         ****      ngen += self.generate(section[subsection], gen_ts)
Jan  8 17:00:21 richard-pc weewx[30139]:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 320, in generate
Jan  8 17:00:21 richard-pc weewx[30139]:         ****      default_binding)
Jan  8 17:00:21 richard-pc weewx[30139]:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 372, in _getSearchList
Jan  8 17:00:21 richard-pc weewx[30139]:         ****      searchList += obj.get_extension_list(timespan, db_lookup)
Jan  8 17:00:21 richard-pc weewx[30139]:         ****    File "/usr/share/weewx/user/belchertown.py", line 588, in get_extension_list
Jan  8 17:00:21 richard-pc weewx[30139]:         ****      output += '<img id="icon" src="'+image_url+'">'
Jan  8 17:00:21 richard-pc weewx[30139]:         ****  UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 68: ordinal not in range(128)
Jan  8 17:00:21 richard-pc weewx[30139]:         ****  Generator terminated
Jan  8 17:00:21 richard-pc weewx[30139]: copygenerator: copied 22 files to /var/www/html/weewx/belchertown
Jan  8 17:01:04 richard-pc weewx[30139]: ftpgenerator: ftp'd 74 files in 43.87 seconds
```

**Comment by poblabs** [comment]
What's your lat lon location? There could be an ascii character in the
forecast?

**Comment by spanishhighs** [comment]
# Latitude and longitude in decimal degrees
    latitude = 36.918
    longitude = -3.469

**Comment by spanishhighs** [comment]
I tried a fresh, clean install of skin.conf and weewx.conf in case I had somehow introduced an erroneous ascii character, but the same error message came up on adding the following to weewx.conf

forecast_enabled = 1
darksky_secret_key = "eg12345678910"

**Comment by spanishhighs** [comment]
Success! After much internet wanderings I seem to have got this working by adding the following into the head of the belchertown.py file

import sys
reload(sys)
sys.setdefaultencoding("utf-8")

Now the conditions work fine on my test site https://www.spanishhighs.co.uk/test/belchertown/

**Comment by poblabs** [comment]
I think you've stumbled upon a few errors I've had reported lately, and maybe even found the fix for it! I'll do some testing (I don't think you need to reload sys) but, if it's working for you, great!

**Comment by poblabs** [comment]
Ah, it does say it's needed. I'll dig in further when I have some time.
Thanks for the tip!
