### ISSUE TITLE
Installation not working

### ISSUE THREAD

**Issue by aetherwizard** [poblabs/weewx-belchertown#467]
Here are the terminal command and results I am getting:

$ sudo wee_extension --install weewx-belchertown-1.2.tar.gz
Request to install 'weewx-belchertown-1.2.tar.gz'
Extracting from tar archive weewx-belchertown-1.2.tar.gz
Traceback (most recent call last):
  File "/usr/share/weewx/wee_extension", line 88, in <module>
    main()
  File "/usr/share/weewx/wee_extension", line 80, in main
    ext.install_extension(options.install)
  File "/usr/share/weewx/weecfg/extension.py", line 115, in install_extension
    member_names = weecfg.extract_tar(extension_path,
  File "/usr/share/weewx/weecfg/__init__.py", line 1794, in extract_tar
    tar_archive = tarfile.open(filename, mode='r')
  File "/usr/lib/python3.8/tarfile.py", line 1606, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully

What do I need to do to get passed this?

**Comment by poblabs** [comment]
This looks like a problem with weewx and not with Belchertown. I'd suggest asking in the user forums for help
