### ISSUE TITLE
UnboundLocalError: local variable 'beaufort0' referenced before assignment

### ISSUE THREAD

**Issue by mercurystorm** [poblabs/weewx-belchertown#526]
Please don't delete these questions! They are asked almost with every issue - answering them as below saves us time from asking them!

**Describe the bug**
Unable to generate report with latest github pull

ERROR weewx.reportengine: Caught unrecoverable exception in generator 'weewx.cheetahgenerator.CheetahGenerator'
Jan 11 23:34:10 rpi-weewx wee_reports[1067] ERROR weewx.reportengine:         ****  local variable 'beaufort0' referenced before assignment
Jan 11 23:34:10 rpi-weewx wee_reports[1067] ERROR weewx.reportengine:         ****  Traceback (most recent call last):
Jan 11 23:34:10 rpi-weewx wee_reports[1067] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 196, in run
Jan 11 23:34:10 rpi-weewx wee_reports[1067] ERROR weewx.reportengine:         ****      obj.start()
Jan 11 23:34:10 rpi-weewx wee_reports[1067] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 281, in start
Jan 11 23:34:10 rpi-weewx wee_reports[1067] ERROR weewx.reportengine:         ****      self.run()
Jan 11 23:34:10 rpi-weewx wee_reports[1067] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 149, in run
Jan 11 23:34:10 rpi-weewx wee_reports[1067] ERROR weewx.reportengine:         ****      ngen = self.generate(gen_dict[section_name], self.gen_ts)
Jan 11 23:34:10 rpi-weewx wee_reports[1067] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 219, in generate
Jan 11 23:34:10 rpi-weewx wee_reports[1067] ERROR weewx.reportengine:         ****      ngen += self.generate(section[subsection], gen_ts)
Jan 11 23:34:10 rpi-weewx wee_reports[1067] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 219, in generate
Jan 11 23:34:10 rpi-weewx wee_reports[1067] ERROR weewx.reportengine:         ****      ngen += self.generate(section[subsection], gen_ts)
Jan 11 23:34:10 rpi-weewx wee_reports[1067] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 308, in generate
Jan 11 23:34:10 rpi-weewx wee_reports[1067] ERROR weewx.reportengine:         ****      default_binding)
Jan 11 23:34:10 rpi-weewx wee_reports[1067] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 379, in _getSearchList
Jan 11 23:34:10 rpi-weewx wee_reports[1067] ERROR weewx.reportengine:         ****      searchList += obj.get_extension_list(timespan, db_lookup)
Jan 11 23:34:10 rpi-weewx wee_reports[1067] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/user/belchertown.py", line 1563, in get_extension_list
Jan 11 23:34:10 rpi-weewx wee_reports[1067] ERROR weewx.reportengine:         ****      'beaufort0': beaufort0,
Jan 11 23:34:10 rpi-weewx wee_reports[1067] ERROR weewx.reportengine:         ****  UnboundLocalError: local variable 'beaufort0' referenced before assignment
Jan 11 23:34:10 rpi-weewx wee_reports[1067] ERROR weewx.reportengine:         ****  Generator terminated

**Version of the skin you're using**
Latest github pull

**To Reproduce**
1. run wee_reports

**Expected behavior**
Reports are generated without error

**Screenshots**

**Device Information (please complete the following information):**
 - Device: [e.g. desktop, iPhone6]
 - OS: [e.g. Windows, Android, iOS]
 - Browser [e.g. Chrome, Safari]

**Additional context**
Add any other context about the problem here. Maybe a potential fix?

**HELP WANTED**
If you have a fix for this, please submit a pull request against the development branch!

**Comment by mercurystorm** [comment]
duplicate
