### ISSUE TITLE
Display the "distance from" in miles for earthquake if not using metric distance

### ISSUE THREAD

**Issue by dkozinn** [poblabs/weewx-belchertown#535]
:bulb: **The Idea**
When using USGS earthquake data, the distance from location is always displayed in km because that's what USGS returns in the  place string. It would be nice if the distance could be converted to miles for those of us using that as our normal distance unit.

I've implemented this by parsing out the "xx km" string from the place string and replacing it with the equivalent in miles. It will only do this if **distance_unit** isn't km and it will also leave the place string unchanged if it can't properly parse out distance (which can happen if there is no distance).

:hammer: **Breaking Feature**
This should not change anything other than have the intended effect.

**HELP WANTED**
I'll be submitting a pull request for this.

**Comment by dkozinn** [comment]
@poblabs I deleted my fork and started from scratch. I've put my code back in but when I run wee_reports as a test I get the following:

```
Using configuration file /etc/weewx/weewx.conf
Generating for all time
Traceback (most recent call last):
  File "/usr/share/weewx/user/belchertown.py", line 1482, in get_extension_list
    aqi = data["aqi"][0]["response"][0]["periods"][0]["aqi"]
KeyError: 'aqi'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/weewx/weewx/reportengine.py", line 196, in run
    obj.start()
  File "/usr/share/weewx/weewx/reportengine.py", line 281, in start
    self.run()
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 149, in run
    ngen = self.generate(gen_dict[section_name], self.gen_ts)
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 219, in generate
    ngen += self.generate(section[subsection], gen_ts)
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 219, in generate
    ngen += self.generate(section[subsection], gen_ts)
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 307, in generate
    searchList = self._getSearchList(encoding, timespan,
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 379, in _getSearchList
    searchList += obj.get_extension_list(timespan, db_lookup)
  File "/usr/share/weewx/user/belchertown.py", line 1490, in get_extension_list
    "The URL being used is:\n%s" % (error, data["aqi"], aqi_url)
KeyError: 'aqi'
```
I've only put my version of belchertown.py into /usr/share/weewx/user, do I need to install any other files to get this to work correctly?

**Comment by poblabs** [comment]
I think that this was fixed recently. Try grabbing a full copy of master again and try again

**Comment by dkozinn** [comment]
Same issue (slightly different line numbers). This time before I edited I just copied belchertown.py to /usr/share/weewx/user and ran wee_reports. Do I need to install anything else or update the config file?

```Using configuration file /etc/weewx/weewx.conf
Generating for all time
Traceback (most recent call last):
  File "/usr/share/weewx/user/belchertown.py", line 1481, in get_extension_list
    aqi = data["aqi"][0]["response"][0]["periods"][0]["aqi"]
KeyError: 'aqi'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/weewx/weewx/reportengine.py", line 196, in run
    obj.start()
  File "/usr/share/weewx/weewx/reportengine.py", line 281, in start
    self.run()
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 150, in run
    ngen = self.generate(gen_dict[section_name], self.gen_ts)
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 220, in generate
    ngen += self.generate(section[subsection], gen_ts)
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 220, in generate
    ngen += self.generate(section[subsection], gen_ts)
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 308, in generate
    searchList = self._getSearchList(encoding, timespan,
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 385, in _getSearchList
    searchList += obj.get_extension_list(timespan, db_lookup)
  File "/usr/share/weewx/user/belchertown.py", line 1489, in get_extension_list
    "The URL being used is:\n%s" % (error, data["aqi"], aqi_url)
KeyError: 'aqi'

**Comment by uajqq** [comment]
Can you delete forecast.json, try wee_reports again, and see what happens (after installing most recent belchertown.py)?

**Comment by dkozinn** [comment]
That worked.  Should I proceed to add my changes back in and submit a pull request then, or is this something that needs to be addressed first?

**Comment by poblabs** [comment]
Go ahead with your changes
