### ISSUE TITLE
Error following PR #562

### ISSUE THREAD

**Issue by ddperso** [poblabs/weewx-belchertown#564]
Following this update I ahve this error after wee_reports:

root@meteo:~# wee_reports
Using configuration file /etc/weewx/weewx.conf
Generating for all time
Traceback (most recent call last):
  File "/usr/share/weewx/weewx/reportengine.py", line 196, in run
    obj.start()
  File "/usr/share/weewx/weewx/reportengine.py", line 281, in start
    self.run()
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 150, in run
    ngen = self.generate(gen_dict[section_name], self.gen_ts)
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 220, in generate
    ngen += self.generate(section[subsection], gen_ts)
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 220, in generate
    ngen += self.generate(section[subsection], gen_ts)
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 309, in generate
    default_binding)
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 385, in _getSearchList
    searchList += obj.get_extension_list(timespan, db_lookup)
  File "/usr/share/weewx/user/belchertown.py", line 507, in get_extension_list
    date_time = "%s/%s/%s 00:00:00" % now.month, now.today, now.year
TypeError: not enough arguments for format string

**Comment by ddperso** [comment]
Sorry I have not seen PR #563....
