### ISSUE TITLE
can't start after fresh install from GitHub 27.feb. - crash with  'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by jovo0911** [poblabs/weewx-belchertown#615]
After update from last GitHub Belchertown crashed with 'NonType'

system run on RP3+ debian Buster

I removed weewx and Belchertown and sqlite DB so OS is without them.

after reboot I install 'weewx(python3)'  again (4.4.0.1) then I install Belchertown 1.2 + MqttSubscribe(2.0.0)
System is starting up an running (delete sqlite DB before)

If I try to install a version later - it's crash! (delete sqlite DB before)

Feb 28 20:40:15 wetterpi weewx[9650] INFO weewx.manager: Added record 2021-02-28 20:40:00 CET (1614541200) to database 'weewx.sdb'
Feb 28 20:40:16 wetterpi weewx[9650] INFO weewx.manager: Added record 2021-02-28 20:40:00 CET (1614541200) to daily summary in 'weewx.sdb'
Feb 28 20:40:17 wetterpi weewx[9650] INFO user.belchertown: version 1.3b1
Feb 28 20:40:17 wetterpi weewx[9650] ERROR weewx.reportengine: Caught unrecoverable exception in generator 'weewx.cheetahgenerator.CheetahGenerator'
Feb 28 20:40:17 wetterpi weewx[9650] ERROR weewx.reportengine:         ****  'NoneType' object is not subscriptable
Feb 28 20:40:18 wetterpi weewx[9650] ERROR weewx.reportengine:         ****  Traceback (most recent call last):
Feb 28 20:40:18 wetterpi weewx[9650] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 196, in run
Feb 28 20:40:18 wetterpi weewx[9650] ERROR weewx.reportengine:         ****      obj.start()
Feb 28 20:40:18 wetterpi weewx[9650] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 281, in start
Feb 28 20:40:18 wetterpi weewx[9650] ERROR weewx.reportengine:         ****      self.run()
Feb 28 20:40:18 wetterpi weewx[9650] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 150, in run
Feb 28 20:40:18 wetterpi weewx[9650] ERROR weewx.reportengine:         ****      ngen = self.generate(gen_dict[section_name], self.gen_ts)
Feb 28 20:40:18 wetterpi weewx[9650] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 220, in generate
Feb 28 20:40:18 wetterpi weewx[9650] ERROR weewx.reportengine:         ****      ngen += self.generate(section[subsection], gen_ts)
Feb 28 20:40:18 wetterpi weewx[9650] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 220, in generate
Feb 28 20:40:18 wetterpi weewx[9650] ERROR weewx.reportengine:         ****      ngen += self.generate(section[subsection], gen_ts)
Feb 28 20:40:18 wetterpi weewx[9650] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 309, in generate
Feb 28 20:40:18 wetterpi weewx[9650] ERROR weewx.reportengine:         ****      default_binding)
Feb 28 20:40:18 wetterpi weewx[9650] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 385, in _getSearchList
Feb 28 20:40:18 wetterpi weewx[9650] ERROR weewx.reportengine:         ****      searchList += obj.get_extension_list(timespan, db_lookup)
Feb 28 20:40:18 wetterpi weewx[9650] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/user/belchertown.py", line 639, in get_extension_list
Feb 28 20:40:18 wetterpi weewx[9650] ERROR weewx.reportengine:         ****      at_outTemp_max_range_query[3],
Feb 28 20:40:18 wetterpi weewx[9650] ERROR weewx.reportengine:         ****  TypeError: 'NoneType' object is not subscriptable
Feb 28 20:40:18 wetterpi weewx[9650] ERROR weewx.reportengine:         ****  Generator terminated

**Comment by jovo0911** [comment]
No install issue with march version. Closed
