### ISSUE TITLE
Forecast output not working

### ISSUE THREAD

**Issue by silke-99** [poblabs/weewx-belchertown#652]
Hello, I love your skin, but I can't seem to get forecasting to work.

I'm using Aeris, and getting forecasts via the forecast module is working. (weewx 4.4.0, python 3)
I'm using belchertown skin version 1.2 which has been newly installed on my older weewx installation.

However, when enabling the Aeris forecast and setting the credentials in skin.conf, at first try (no forecast.json existing), there's this error:

Caught unrecoverable exception in generator 'weewx.cheetahgenerator.CheetahGenerator'
Mar 23 10:36:57 bella python3[582612]: weewx[582612] ERROR weewx.reportengine:         ****  local variable 'forecast_file_result' referenced before assignment
Mar 23 10:36:57 bella python3[582612]: weewx[582612] ERROR weewx.reportengine:         ****  Traceback (most recent call last):
Mar 23 10:36:57 bella python3[582612]: weewx[582612] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/user/belchertown.py", line 978, in get_extension_list
Mar 23 10:36:57 bella python3[582612]: weewx[582612] ERROR weewx.reportengine:         ****      file.write( forecast_file_result.encode('utf-8') )
Mar 23 10:36:57 bella python3[582612]: weewx[582612] ERROR weewx.reportengine:         ****  UnboundLocalError: local variable 'forecast_file_result' referenced before assignment

Then, an empty forecast.json is created and subsequent runs are throwing this error:

Mar 23 10:45:33 bella python3[582612]: weewx[582612] ERROR weewx.reportengine:         ****    File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
Mar 23 10:45:33 bella python3[582612]: weewx[582612] ERROR weewx.reportengine:         ****      raise JSONDecodeError("Expecting value", s, err.value) from None
Mar 23 10:45:33 bella python3[582612]: weewx[582612] ERROR weewx.reportengine:         ****  json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Mar 23 10:45:33 bella python3[582612]: weewx[582612] ERROR weewx.reportengine:         ****  Generator terminated

Probably due to the empty json file. Any idea?

**Comment by silke-99** [comment]
Update: After uninstalling/reinstalling the skin from scratch and deleting the empty forecast.json, it works! 
Not sure where exactly I went wrong here...
