### ISSUE TITLE
Belchertown does not work with wview_small.py db schema

### ISSUE THREAD

**Issue by bdf0506** [poblabs/weewx-belchertown#700]
A few months back, the schema of wview_small.py was [introduced](https://github.com/weewx/weewx/blob/master/bin/schemas/wview_small.py), but unfortunately this schema doesn't appear to be supported by Belchertown.

You get errors similar to the following:
````
Jul  4 22:25:20 weewx[17] ERROR weewx.cheetahgenerator: Generate failed with exception '<class 'TypeError'>'
Jul  4 22:25:20 weewx[17] ERROR weewx.cheetahgenerator: **** Ignoring template /home/weewx/skins/Belchertown/about/index.html.tmpl
Jul  4 22:25:20 weewx[17] ERROR weewx.cheetahgenerator: **** Reason: 'UnknownType' object is not subscriptable
Jul  4 22:25:20 weewx[17] ERROR weewx.cheetahgenerator: ****  Traceback (most recent call last):
Jul  4 22:25:20 weewx[17] ERROR weewx.cheetahgenerator: ****    File "/home/weewx/bin/weewx/cheetahgenerator.py", line 326, in generate
Jul  4 22:25:20 weewx[17] ERROR weewx.cheetahgenerator: ****      unicode_string = compiled_template.respond()
Jul  4 22:25:20 weewx[17] ERROR weewx.cheetahgenerator: ****    File "_home_weewx_skins_Belchertown_about_index_html_tmpl.py", line 104, in respond
Jul  4 22:25:20 weewx[17] ERROR weewx.cheetahgenerator: ****    File "/home/weewx/bin/Cheetah/Template.py", line 1708, in _handleCheetahInclude
Jul  4 22:25:20 weewx[17] ERROR weewx.cheetahgenerator: ****      self._CHEETAH__cheetahIncludes[_includeID].respond(trans)
Jul  4 22:25:20 weewx[17] ERROR weewx.cheetahgenerator: ****    File "_home_weewx_skins_Belchertown_about_inc.py", line 173, in respond
Jul  4 22:25:20 weewx[17] ERROR weewx.cheetahgenerator: ****    File "/home/weewx/bin/weewx/units.py", line 1197, in raw
Jul  4 22:25:20 weewx[17] ERROR weewx.cheetahgenerator: ****      return self.value_t[0]
Jul  4 22:25:20 weewx[17] ERROR weewx.cheetahgenerator: ****  TypeError: 'UnknownType' object is not subscriptable
Jul  4 22:25:20 weewx[17] INFO weewx.cheetahgenerator: Generated 10 files for report Belchertown in 0.57 seconds````

Not sure if this error is fatal or not - appears to be non fatal. But documentation should be updated to indicate that the standard wview.py schema is required at a bare minimum. Or something should be done to suppress these error messages if they aren't fatal.

**Comment by poblabs** [comment]
This looks like a Unicode problem in the about page template and not a
schema issue

**Comment by bdf0506** [comment]
I think it is somehow a schema issue. All things equal, if I spin up a new weewx instance with wview_extended.py that error message goes away. I spin it up again with wview_small.py, and the error shows up again.

**Comment by bdf0506** [comment]
I apologize, this was my error. I thought I was trying this with a fresh install, but was actually using this with an install that had a custom page in the about.inc page, which was then referencing a db field that didn't exist in wview_small.py. So after all, wview_small.py does in fact work with Belchertown.
