### ISSUE TITLE
weewx.cheetahgenerator: Generate failed with exception '<class 'NameMapper.NotFound'>'

### ISSUE THREAD

**Issue by kalju** [poblabs/weewx-belchertown#702]
Hi gurus,

Moved my weewx from pi3 to pi4.
Installed fresh weewx 4.5.1 and 1.3b1 skin
Now I'm suddenly facing error in logs on new installation on pi4:

```
weewx[14008] ERROR weewx.cheetahgenerator: Generate failed with exception '<class 'NameMapper.NotFound'>'
weewx[14008] ERROR weewx.cheetahgenerator: **** Ignoring template /etc/weewx/skins/Belchertown/NOAA/NOAA-YYYY-MM.txt.tmpl
weewx[14008] ERROR weewx.cheetahgenerator: **** Reason: cannot find 'raw' while searching for 'day.wind.count.raw'
weewx[14008] ERROR weewx.cheetahgenerator: ****  Traceback (most recent call last):
weewx[14008] ERROR weewx.cheetahgenerator: ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 326, in generate
weewx[14008] ERROR weewx.cheetahgenerator: ****      unicode_string = compiled_template.respond()
weewx[14008] ERROR weewx.cheetahgenerator: ****    File "_etc_weewx_skins_Belchertown_NOAA_NOAA_YYYY_MM_txt_tmpl.py", line 431, in respond
weewx[14008] ERROR weewx.cheetahgenerator: ****  NameMapper.NotFound: cannot find 'raw' while searching for 'day.wind.count.raw'

weewx[16323] ERROR weewx.cheetahgenerator: Generate failed with exception '<class 'NameMapper.NotFound'>'
weewx[16323] ERROR weewx.cheetahgenerator: **** Ignoring template /etc/weewx/skins/Belchertown/NOAA/NOAA-YYYY.txt.tmpl
weewx[16323] ERROR weewx.cheetahgenerator: **** Reason: cannot find 'raw' while searching for 'month.wind.count.raw'
weewx[16323] ERROR weewx.cheetahgenerator: ****  Traceback (most recent call last):
weewx[16323] ERROR weewx.cheetahgenerator: ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 326, in generate
weewx[16323] ERROR weewx.cheetahgenerator: ****      unicode_string = compiled_template.respond()
weewx[16323] ERROR weewx.cheetahgenerator: ****    File "_etc_weewx_skins_Belchertown_NOAA_NOAA_YYYY_txt_tmpl.py", line 862, in respond
weewx[16323] ERROR weewx.cheetahgenerator: ****  NameMapper.NotFound: cannot find 'raw' while searching for 'month.wind.count.raw'
```
No errors in logs on old pi3 installation.
Can not find any differences in conf files between pi3 and pi4.
Any idea what causes that?
Thanks in advance

**Comment by kalju** [comment]
Update: figured it out. weewx.sdb was corrupted. 
Case closed.
