### ISSUE TITLE
Error trying to use database binding wx_binding to graph observation outTemp

### ISSUE THREAD

**Issue by dtalens** [poblabs/weewx-belchertown#715]
Please don't delete these questions! They are asked almost with every issue - answering them as below saves us time from asking them!

**First step**
Try to debug the skin yourself. If you can't figure it out, please include the debug information (text, screenshots, etc.). See this guide on debugging the skin. https://github.com/poblabs/weewx-belchertown#how-to-use-debug

**Describe the bug**
I don't know because appears this error.
`
Sep 22 11:14:22 minipc weewx[1899] ERROR weewx.reportengine: Caught unrecoverable exception in generator 'user.belchertown.HighchartsJsonGenerator'
Sep 22 11:14:22 minipc weewx[1899] ERROR weewx.reportengine:         ****  Error trying to use database binding wx_binding to graph observation outTemp. Error was: 'int' object has no attribute 'lower'.
Sep 22 11:14:22 minipc weewx[1899] ERROR weewx.reportengine:         ****  Traceback (most recent call last):
Sep 22 11:14:22 minipc weewx[1899] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/user/belchertown.py", line 3214, in get_observation_data
Sep 22 11:14:22 minipc weewx[1899] ERROR weewx.reportengine:         ****      )
Sep 22 11:14:22 minipc weewx[1899] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/xtypes.py", line 87, in get_series
Sep 22 11:14:22 minipc weewx[1899] ERROR weewx.reportengine:         ****      return xtype.get_series(obs_type, timespan, db_manager, aggregate_type,
Sep 22 11:14:22 minipc weewx[1899] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/xtypes.py", line 526, in get_series
Sep 22 11:14:22 minipc weewx[1899] ERROR weewx.reportengine:         ****      aggregate_type = aggregate_type.lower()
Sep 22 11:14:22 minipc weewx[1899] ERROR weewx.reportengine:         ****  AttributeError: 'int' object has no attribute 'lower'
Sep 22 11:14:22 minipc weewx[1899] ERROR weewx.reportengine:         ****  
Sep 22 11:14:22 minipc weewx[1899] ERROR weewx.reportengine:         ****  During handling of the above exception, another exception occurred:
Sep 22 11:14:22 minipc weewx[1899] ERROR weewx.reportengine:         ****  
Sep 22 11:14:22 minipc weewx[1899] ERROR weewx.reportengine:         ****  Traceback (most recent call last):
Sep 22 11:14:22 minipc weewx[1899] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 196, in run
Sep 22 11:14:22 minipc weewx[1899] ERROR weewx.reportengine:         ****      obj.start()
Sep 22 11:14:22 minipc weewx[1899] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 281, in start
Sep 22 11:14:22 minipc weewx[1899] ERROR weewx.reportengine:         ****      self.run()
Sep 22 11:14:22 minipc weewx[1899] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/user/belchertown.py", line 2684, in run
Sep 22 11:14:22 minipc weewx[1899] ERROR weewx.reportengine:         ****      else:
Sep 22 11:14:22 minipc weewx[1899] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/user/belchertown.py", line 3222, in get_observation_data
Sep 22 11:14:22 minipc weewx[1899] ERROR weewx.reportengine:         ****  Warning: Error trying to use database binding wx_binding to graph observation outTemp. Error was: 'int' object has no attribute 'lower'.
Sep 22 11:14:22 minipc weewx[1899] ERROR weewx.reportengine:         ****  Generator terminated
`

**Link to your website (IMPORTANT)**
[https://meteopego.com/](https://meteopego.com/)
In web console not appear errors.

**Version of the skin you're using**
1.3b

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information (please complete the following information):**
 - Device: [e.g. desktop, iPhone6]
 - OS: [e.g. Windows, Android, iOS]
 - Browser [e.g. Chrome, Safari]

**Additional context**
Add any other context about the problem here. Maybe a potential fix?

**HELP WANTED**
If you have a fix for this, please submit a pull request against the development branch!

**Comment by dtalens** [comment]
It is not a problem related to skin but to the database. I solved it with a rebuild database.
