### ISSUE TITLE
Missing current conditions in my location

### ISSUE THREAD

**Issue by dtalens** [poblabs/weewx-belchertown#821]
**Describe the bug**
In my location I only have current conditions data and icons if I have `forecast_aeris_use_metar` option activated. The problem is that location of the nearest METAR station (airport) is more than 60 km from my location and therefore the weather forecasts are not very accurate. If I disable the `forecast_aeris_use_metar` option, icons and current weather forecast disappear.

**Link to your website (IMPORTANT)**
https://meteopego.com/

**Version of the skin you're using**
1.3b1

**Additional context**
I have reviewed aerisweather API documentation and am wondering if it is possible to use
[Endpoint: conditions](https://www.aerisweather.com/support/docs/api/reference/endpoints/conditions/) instead of [Endpoint: Observations](https://www.aerisweather.com/support/docs/api/reference/endpoints/observations/). If Endpoint conditions is used if forecast data and icons are obtained of stations close to my location.
![image](https://user-images.githubusercontent.com/6631832/192346203-bc6a2039-027b-4bf9-99a8-544e0bfe82b5.png)

**Comment by dtalens** [comment]
Ei, I need help to rewritte code for Conditions EndPoint. I created this branch: [https://github.com/dtalens/weewx-belchertown/tree/aerisweather-forecast-alternative](https://github.com/dtalens/weewx-belchertown/tree/aerisweather-forecast-alternative)

**Comment by dtalens** [comment]
I don't know how to read json array strings from Aerisweather Conditions EndPoint... any help?
```
oct 20 12:56:26 minipc weewx[82988] ERROR weewx.reportengine: Caught unrecoverable exception in generator 'weewx.cheetahgenerator.CheetahGenerator'
Oct 20 12:56:26 minipc weewx[82988] ERROR weewx.reportengine:         ****  'periods'
Oct 20 12:56:26 minipc weewx[82988] ERROR weewx.reportengine:         ****  Traceback (most recent call last):
Oct 20 12:56:26 minipc weewx[82988] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 197, in run
Oct 20 12:56:26 minipc weewx[82988] ERROR weewx.reportengine:         ****      obj.start()
Oct 20 12:56:26 minipc weewx[82988] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 385, in start
Oct 20 12:56:26 minipc weewx[82988] ERROR weewx.reportengine:         ****      self.run()
Oct 20 12:56:26 minipc weewx[82988] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 169, in run
Oct 20 12:56:26 minipc weewx[82988] ERROR weewx.reportengine:         ****      ngen = self.generate(gen_dict[section_name], section_name, self.gen_ts)
Oct 20 12:56:26 minipc weewx[82988] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 229, in generate
Oct 20 12:56:26 minipc weewx[82988] ERROR weewx.reportengine:         ****      ngen += self.generate(section[subsection], subsection, gen_ts)
Oct 20 12:56:26 minipc weewx[82988] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 229, in generate
Oct 20 12:56:26 minipc weewx[82988] ERROR weewx.reportengine:         ****      ngen += self.generate(section[subsection], subsection, gen_ts)
Oct 20 12:56:26 minipc weewx[82988] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 321, in generate
Oct 20 12:56:26 minipc weewx[82988] ERROR weewx.reportengine:         ****      searchList = self._getSearchList(encoding, timespan,
Oct 20 12:56:26 minipc weewx[82988] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 415, in _getSearchList
Oct 20 12:56:26 minipc weewx[82988] ERROR weewx.reportengine:         ****      search_list += obj.get_extension_list(timespan, db_lookup)
Oct 20 12:56:26 minipc weewx[82988] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/user/belchertown.py", line 1512, in get_extension_list
Oct 20 12:56:26 minipc weewx[82988] ERROR weewx.reportengine:         ****      data["current"][0]["response"]["periods"]["weatherPrimaryCoded"]
Oct 20 12:56:26 minipc weewx[82988] ERROR weewx.reportengine:         ****  KeyError: 'periods'
Oct 20 12:56:26 minipc weewx[82988] ERROR weewx.reportengine:         ****  Generator terminated
```

**Comment by dtalens** [comment]
I've created an [alternative branch ](https://github.com/poblabs/weewx-belchertown/commit/6b06e371f5b9b446b0e310bbc1f6ca19ba4f4b8a) where I've replaced Observations endpoint with Conditions endpoint. I removed `forecast_aeris_use_metar` option because I couldn't add it. Anyone care to fix this to work with both endpoints so I can push it to the master branch?
