### ISSUE TITLE
No forecast data

### ISSUE THREAD

**Issue by kalju** [poblabs/weewx-belchertown#851]
Hi all,

Suddenly, about a week ago I lost forecast information.
Also, the current weather icon is missing since about a week ago.

<img width="1239" alt="weewx" src="https://user-images.githubusercontent.com/31128780/209443247-4ebd71a2-4942-4c0d-8260-ddc397d85b82.png">

No changes were made on Weewx install prior to loosing forecast.

Metar is set in skin.conf as "forecast_aeris_use_metar = 1"
I have tried disable metar but it makes no difference.

forecast.json gives following output:
`{
    "timestamp": 1671892220,
    "current": [
        {
            "success": true,
            "error": {
                "code": "warn_no_data",
                "description": "Valid request. No results available based on your query parameters."
            },
            "response": []
        }
`
However, forecast.json has all the forecast data, see attached
[forecast.txt](https://github.com/poblabs/weewx-belchertown/files/10298774/forecast.txt)

Aeris API returns forecast data both on lat/long as well as on location requests:
https://api.aerisapi.com/forecasts/varbola,ee?format=json&filter=detailed&limit=7&client_id=[CLIENT_ID]&client_secret=[CLIENT_SECRET]
https://api.aerisapi.com/forecasts/59.043,24.449?format=json&filter=detailed&limit=7&client_id=[CLIENT_ID]&client_secret=[CLIENT_SECRET]

From https://ilm.oruniidu.ee/?debug=true I can see error:

`Uncaught TypeError: Cannot read properties of undefined (reading 'icon')
    at Object.update_forecast_data [as success] (belchertown.js?1671890725:1169:103)
    at u (jquery.min.js:2:27457)
    at Object.fireWith [as resolveWith] (jquery.min.js:2:28202)
    at k (jquery.min.js:2:77651)
    at XMLHttpRequest.<anonymous> (jquery.min.js:2:79907)`

Any ideas what's wrong?

Thanks in advance.

/Kalju

And Merry Christmas everybody!

**Comment by kalju** [comment]
Well...

When I'm using API calls (either with latitude/longitude or location - varbola,ee):
https://api.aerisapi.com/observations/varbola,ee?format=json&filter=detailed&limit=7&client_id=[CLIENT_ID]&client_secret=[CLIENT_SECRET]
or
https://api.aerisapi.com/observations/59.043,24.528?format=json&filter=detailed&limit=7&client_id=[CLIENT_ID]&client_secret=[CLIENT_SECRET]
or
https://api.aerisapi.com/observations/closest?p=varbola,ee&format=json&radius=25mi&filter=allstations&limit=10&[CLIENT_ID]&client_secret=[CLIENT_SECRET]
or
https://api.aerisapi.com/observations/closest?p=59.043,24.528&format=json&radius=25mi&filter=allstations&limit=10&[CLIENT_ID]&client_secret=[CLIENT_SECRET]

the response is always the same:
`{"success":true,"error":{"code":"warn_no_data","description":"Valid request. No results available based on your query parameters."},"response":[]}`

This response is supposed to mean that there is no data available for that location (within 25 miles). No data for Estonia at all it seems (even for the capital city)

However, if I'm using AerisWeather URL https://www.aerisweather.com/weather/local/ee/varbola it shows the location and the observation.

So it seems like the forecast API calls are returning correct replies but the observation API calls are failing with error "no data".

Will talk to AerisWeather and will report back.

**Comment by kalju** [comment]
Oh, well. 
Seems like AerisWeather messed up with observation endpoint in their API. API response shows no stations in Estonia (neither METAR nor PWS). Given that we have 6 airports with METAR data and bunch of private stations reporting to PWS (including me) this is surprising to say the least.
At this time there is no hope that it would be fixed soon.

Switched to [alternative branch](https://github.com/poblabs/weewx-belchertown/issues/821) where observation endpoint is replaced with conditions endpoint.
Thanks [dtalens](https://github.com/dtalens)!
