### ISSUE TITLE
Bug after upgrade to V1.3 

### ISSUE THREAD

**Issue by Bug-Storm** [poblabs/weewx-belchertown#867]
**Describe the bug**

```
Mar  2 20:35:36 raspberrypi weewx[14159] DEBUG weewx.manager: Daily summary version is 4.0
Mar  2 20:35:38 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: Generate failed with exception '<class 'NameMapper.NotFound'>'
Mar  2 20:35:38 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: **** Ignoring template /etc/weewx/skins/Belchertown/index.html.tmpl
Mar  2 20:35:38 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: **** Reason: cannot find 'filename'
Mar  2 20:35:38 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: ****  Traceback (most recent call last):
Mar  2 20:35:38 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 326, in generate
Mar  2 20:35:38 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: ****      unicode_string = compiled_template.respond()
Mar  2 20:35:38 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: ****    File "cheetah__etc_weewx_skins_Belchertown_index_html_tmpl_1677785438_0213225_49792.py", line 700, in respond
Mar  2 20:35:38 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: ****    File "/usr/lib/python3/dist-packages/Cheetah/Template.py", line 1708, in _handleCheetahInclude
Mar  2 20:35:38 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: ****      self._CHEETAH__cheetahIncludes[_includeID].respond(trans)
Mar  2 20:35:38 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: ****    File "cheetah__etc_weewx_skins_Belchertown_header_html_tmpl_1677785438_1459296_94811.py", line 152, in respond
Mar  2 20:35:38 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: ****  NameMapper.NotFound: cannot find 'filename'
Mar  2 20:35:38 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: Generate failed with exception '<class 'NameMapper.NotFound'>'
Mar  2 20:35:38 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: **** Ignoring template /etc/weewx/skins/Belchertown/about/index.html.tmpl
Mar  2 20:35:38 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: **** Reason: cannot find 'filename'
Mar  2 20:35:38 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: ****  Traceback (most recent call last):
Mar  2 20:35:38 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 326, in generate
Mar  2 20:35:38 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: ****      unicode_string = compiled_template.respond()
Mar  2 20:35:38 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: ****    File "cheetah__etc_weewx_skins_Belchertown_about_index_html_tmpl_1677785438_2801807_85122.py", line 93, in respond
Mar  2 20:35:38 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: ****    File "/usr/lib/python3/dist-packages/Cheetah/Template.py", line 1708, in _handleCheetahInclude
Mar  2 20:35:38 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: ****      self._CHEETAH__cheetahIncludes[_includeID].respond(trans)
Mar  2 20:35:38 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: ****    File "cheetah__etc_weewx_skins_Belchertown_header_html_tmpl_1677785438_1459296_94811.py", line 152, in respond
Mar  2 20:35:38 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: ****  NameMapper.NotFound: cannot find 'filename'
Mar  2 20:35:39 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: Generate failed with exception '<class 'NameMapper.NotFound'>'
Mar  2 20:35:39 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: **** Ignoring template /etc/weewx/skins/Belchertown/graphs/index.html.tmpl
Mar  2 20:35:39 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: **** Reason: cannot find 'filename'
Mar  2 20:35:39 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: ****  Traceback (most recent call last):
Mar  2 20:35:39 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 326, in generate
Mar  2 20:35:39 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: ****      unicode_string = compiled_template.respond()
Mar  2 20:35:39 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: ****    File "cheetah__etc_weewx_skins_Belchertown_graphs_index_html_tmpl_1677785438_4315226_27171.py", line 114, in respond
Mar  2 20:35:39 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: ****    File "/usr/lib/python3/dist-packages/Cheetah/Template.py", line 1708, in _handleCheetahInclude
Mar  2 20:35:39 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: ****      self._CHEETAH__cheetahIncludes[_includeID].respond(trans)
Mar  2 20:35:39 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: ****    File "cheetah__etc_weewx_skins_Belchertown_header_html_tmpl_1677785438_1459296_94811.py", line 152, in respond
Mar  2 20:35:39 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: ****  NameMapper.NotFound: cannot find 'filename'
Mar  2 20:35:39 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: Generate failed with exception '<class 'NameMapper.NotFound'>'
Mar  2 20:35:39 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: **** Ignoring template /etc/weewx/skins/Belchertown/records/index.html.tmpl
Mar  2 20:35:39 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: **** Reason: cannot find 'filename'
Mar  2 20:35:39 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: ****  Traceback (most recent call last):
Mar  2 20:35:39 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 326, in generate
Mar  2 20:35:39 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: ****      unicode_string = compiled_template.respond()
Mar  2 20:35:39 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: ****    File "cheetah__etc_weewx_skins_Belchertown_records_index_html_tmpl_1677785438_7349799_69238.py", line 1104, in respond
Mar  2 20:35:39 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: ****    File "/usr/lib/python3/dist-packages/Cheetah/Template.py", line 1708, in _handleCheetahInclude
Mar  2 20:35:39 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: ****      self._CHEETAH__cheetahIncludes[_includeID].respond(trans)
Mar  2 20:35:39 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: ****    File "cheetah__etc_weewx_skins_Belchertown_header_html_tmpl_1677785438_1459296_94811.py", line 152, in respond
Mar  2 20:35:39 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: ****  NameMapper.NotFound: cannot find 'filename'
Mar  2 20:35:39 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: Generate failed with exception '<class 'NameMapper.NotFound'>'
Mar  2 20:35:39 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: **** Ignoring template /etc/weewx/skins/Belchertown/reports/index.html.tmpl
Mar  2 20:35:39 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: **** Reason: cannot find 'filename'
Mar  2 20:35:39 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: ****  Traceback (most recent call last):
Mar  2 20:35:39 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 326, in generate
Mar  2 20:35:39 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: ****      unicode_string = compiled_template.respond()
Mar  2 20:35:39 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: ****    File "cheetah__etc_weewx_skins_Belchertown_reports_index_html_tmpl_1677785438_9169688_80301.py", line 135, in respond
Mar  2 20:35:39 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: ****    File "/usr/lib/python3/dist-packages/Cheetah/Template.py", line 1708, in _handleCheetahInclude
Mar  2 20:35:39 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: ****      self._CHEETAH__cheetahIncludes[_includeID].respond(trans)
Mar  2 20:35:39 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: ****    File "cheetah__etc_weewx_skins_Belchertown_header_html_tmpl_1677785438_1459296_94811.py", line 152, in respond
Mar  2 20:35:39 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: ****  NameMapper.NotFound: cannot find 'filename'
Mar  2 20:35:39 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: Generate failed with exception '<class 'NameMapper.NotFound'>'
Mar  2 20:35:39 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: **** Ignoring template /etc/weewx/skins/Belchertown/pi/index.html.tmpl
Mar  2 20:35:39 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: **** Reason: cannot find 'filename'
Mar  2 20:35:39 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: ****  Traceback (most recent call last):
Mar  2 20:35:39 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 326, in generate
Mar  2 20:35:39 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: ****      unicode_string = compiled_template.respond()
Mar  2 20:35:39 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: ****    File "cheetah__etc_weewx_skins_Belchertown_pi_index_html_tmpl_1677785439_1268528_47970.py", line 374, in respond
Mar  2 20:35:39 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: ****    File "/usr/lib/python3/dist-packages/Cheetah/Template.py", line 1708, in _handleCheetahInclude
Mar  2 20:35:39 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: ****      self._CHEETAH__cheetahIncludes[_includeID].respond(trans)
Mar  2 20:35:39 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: ****    File "cheetah__etc_weewx_skins_Belchertown_header_html_tmpl_1677785438_1459296_94811.py", line 152, in respond
Mar  2 20:35:39 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: ****  NameMapper.NotFound: cannot find 'filename'
Mar  2 20:35:39 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: Generate failed with exception '<class 'NameMapper.NotFound'>'
Mar  2 20:35:39 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: **** Ignoring template /etc/weewx/skins/Belchertown/kiosk.html.tmpl
Mar  2 20:35:39 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: **** Reason: cannot find 'filename'
Mar  2 20:35:39 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: ****  Traceback (most recent call last):
Mar  2 20:35:39 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 326, in generate
Mar  2 20:35:39 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: ****      unicode_string = compiled_template.respond()
Mar  2 20:35:39 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: ****    File "cheetah__etc_weewx_skins_Belchertown_kiosk_html_tmpl_1677785439_444893_38245.py", line 455, in respond
Mar  2 20:35:39 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: ****    File "/usr/lib/python3/dist-packages/Cheetah/Template.py", line 1708, in _handleCheetahInclude
Mar  2 20:35:39 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: ****      self._CHEETAH__cheetahIncludes[_includeID].respond(trans)
Mar  2 20:35:39 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: ****    File "cheetah__etc_weewx_skins_Belchertown_header_html_tmpl_1677785438_1459296_94811.py", line 152, in respond
Mar  2 20:35:39 raspberrypi weewx[14159] ERROR weewx.cheetahgenerator: ****  NameMapper.NotFound: cannot find 'filename'
```

**Link to your website (IMPORTANT)**

https://meteo-tethieu.fr/Weewx/belchertown/ 

Last update after upgrade.  

**Version of the skin you're using**
V1.3 
Weewx version = 4.1.1

**To Reproduce**
It's a clear Version after try to upgrade i uninstall et reinstall . I deleted all files 

**Expected behavior**

I just run weewx, no modification on all files 

**Screenshots**

**Device Information (please complete the following information):**
Weewx

**Additional context**
Add any other context about the problem here. Maybe a potential fix?

**HELP WANTED**
If you have a fix for this, please submit a pull request against the development branch!

**Comment by Bug-Storm** [comment]
I update weewx to V 4.10.2 and it's work fine :) .  I think the Version 4.1.1 is too old  and doesn't work with the last version Belchertwon

**Comment by norecords** [comment]
Thanks for reports, it means that we have to change the minimum version of weewx in the README
