### ISSUE TITLE
Kiosk.html not updating

### ISSUE THREAD

**Issue by ChrisM510** [poblabs/weewx-belchertown#919]
**Describe the bug**
Kiosk.html doesn't update after making changes to kiosk.html.tmpl

**Version of the skin you're using**
1.3.1

**Expected behavior**
I expected that changes to the template file would be reflected in the kiosk.html file, just as other changes are made.

**Comment by ChrisM510** [comment]
Ping...

**Comment by ThePeePs** [comment]
what did you change in the template?

**Comment by ChrisM510** [comment]
Its at the default now.  Making changes had no effect...I had to make changes to the kiosk.html file itself that was created during the install.

**Comment by ChrisM510** [comment]
I know that....thats what I am saying...it is never updating.  It made the kisok.html file on install, and that was it.  Any recommendations on where to look to figure out what is/isn't going on?  (BTW, thanks for replying, I do appreciate it.)

**Comment by ThePeePs** [comment]
Does the main page (index.html) get updated like it should?

**Comment by ChrisM510** [comment]
Yes.  Literally everything else is working as it should.

**Comment by ThePeePs** [comment]
are there any errors or warnings in the weewx log file?

**Comment by ChrisM510** [comment]
Took me a while to parse through it (113MB), but I think I found something (below).  Thoughts?

```
2024-01-08T16:15:27.965825-05:00 weather weewx[132051] ERROR weewx.cheetahgenerator: Compilation of template /etc/weewx/skins/Belchertown/kiosk.html.tmpl failed with exception '<class 'Cheetah.Parser.ParseError'>'
2024-01-08T16:15:27.966561-05:00 weather weewx[132051] ERROR weewx.cheetahgenerator: **** Ignoring template /etc/weewx/skins/Belchertown/kiosk.html.tmpl
2024-01-08T16:15:27.967605-05:00 weather weewx[132051] ERROR weewx.cheetahgenerator: **** Reason: #012#012Some #directives are missing their corresponding #end ___ tag: if#012Line 465, column 33 in file /etc/weewx/skins/Belchertown/kiosk.html.tmpl#012#012Line|Cheetah Code#012----|-------------------------------------------------------------#012462 |        </main>#012463 |    </div>#012464 |#012465 |    #include "footer.html.tmpl" #012                                     ^
2024-01-08T16:15:27.972720-05:00 weather weewx[132051] ERROR weewx.cheetahgenerator: ****  Traceback (most recent call last):
2024-01-08T16:15:27.973184-05:00 weather weewx[132051] ERROR weewx.cheetahgenerator: ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 332, in generate
2024-01-08T16:15:27.973580-05:00 weather weewx[132051] ERROR weewx.cheetahgenerator: ****      compiled_template = Cheetah.Template.Template(
2024-01-08T16:15:27.973972-05:00 weather weewx[132051] ERROR weewx.cheetahgenerator: ****                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-08T16:15:27.974642-05:00 weather weewx[132051] ERROR weewx.cheetahgenerator: ****    File "/usr/lib/python3/dist-packages/Cheetah/Template.py", line 1337, in __init__
2024-01-08T16:15:27.975217-05:00 weather weewx[132051] ERROR weewx.cheetahgenerator: ****      self._compile(source, file, compilerSettings=compilerSettings)
2024-01-08T16:15:27.975766-05:00 weather weewx[132051] ERROR weewx.cheetahgenerator: ****    File "/usr/lib/python3/dist-packages/Cheetah/Template.py", line 1634, in _compile
2024-01-08T16:15:27.976916-05:00 weather weewx[132051] ERROR weewx.cheetahgenerator: ****      templateClass = self.compile(source, file,
2024-01-08T16:15:27.977182-05:00 weather weewx[132051] ERROR weewx.cheetahgenerator: ****                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-08T16:15:27.977304-05:00 weather weewx[132051] ERROR weewx.cheetahgenerator: ****    File "/usr/lib/python3/dist-packages/Cheetah/Template.py", line 775, in compile
2024-01-08T16:15:27.977407-05:00 weather weewx[132051] ERROR weewx.cheetahgenerator: ****      compiler.compile()
2024-01-08T16:15:27.977504-05:00 weather weewx[132051] ERROR weewx.cheetahgenerator: ****    File "/usr/lib/python3/dist-packages/Cheetah/Compiler.py", line 1810, in compile
2024-01-08T16:15:27.977673-05:00 weather weewx[132051] ERROR weewx.cheetahgenerator: ****      self._parser.parse()
2024-01-08T16:15:27.977820-05:00 weather weewx[132051] ERROR weewx.cheetahgenerator: ****    File "/usr/lib/python3/dist-packages/Cheetah/Parser.py", line 1561, in parse
2024-01-08T16:15:27.977980-05:00 weather weewx[132051] ERROR weewx.cheetahgenerator: ****      self.assertEmptyOpenDirectivesStack()
2024-01-08T16:15:27.978152-05:00 weather weewx[132051] ERROR weewx.cheetahgenerator: ****    File "/usr/lib/python3/dist-packages/Cheetah/Parser.py", line 2785, in assertEmptyOpenDirectivesStack
2024-01-08T16:15:27.978293-05:00 weather weewx[132051] ERROR weewx.cheetahgenerator: ****      raise ParseError(self, msg=errorMsg)
2024-01-08T16:15:27.978406-05:00 weather weewx[132051] ERROR weewx.cheetahgenerator: ****  Cheetah.Parser.ParseError: 
2024-01-08T16:15:27.978556-05:00 weather weewx[132051] ERROR weewx.cheetahgenerator: ****  
2024-01-08T16:15:27.978734-05:00 weather weewx[132051] ERROR weewx.cheetahgenerator: ****  Some #directives are missing their corresponding #end ___ tag: if
2024-01-08T16:15:27.978851-05:00 weather weewx[132051] ERROR weewx.cheetahgenerator: ****  Line 465, column 33 in file /etc/weewx/skins/Belchertown/kiosk.html.tmpl
2024-01-08T16:15:27.978952-05:00 weather weewx[132051] ERROR weewx.cheetahgenerator: ****  
2024-01-08T16:15:27.979054-05:00 weather weewx[132051] ERROR weewx.cheetahgenerator: ****  Line|Cheetah Code
2024-01-08T16:15:27.979178-05:00 weather weewx[132051] ERROR weewx.cheetahgenerator: ****  ----|-------------------------------------------------------------
2024-01-08T16:15:27.979725-05:00 weather weewx[132051] ERROR weewx.cheetahgenerator: ****  462 |        </main>
2024-01-08T16:15:27.980063-05:00 weather weewx[132051] ERROR weewx.cheetahgenerator: ****  463 |    </div>
2024-01-08T16:15:27.980192-05:00 weather weewx[132051] ERROR weewx.cheetahgenerator: ****  464 |
2024-01-08T16:15:27.980288-05:00 weather weewx[132051] ERROR weewx.cheetahgenerator: ****  465 |    #include "footer.html.tmpl" 
2024-01-08T16:15:27.980392-05:00 weather weewx[132051] ERROR weewx.cheetahgenerator: ****                                       ^
2024-01-08T16:15:27.980512-05:00 weather weewx[132051] ERROR weewx.cheetahgenerator: ****  
2024-01-08T16:15:28.044969-05:00 weather weewx[132051] INFO weewx.cheetahgenerator: Generated 11 files for report Belchertown in 2.98 seconds
2024-01-08T16:15:28.052871-05:00 weather weewx[132051] INFO weewx.reportengine: Copied 3 files to /var/www/html

```

**Comment by ThePeePs** [comment]
Looks like an `#end if` might be missing.  Since it doesn't say what `#if` it's looking at, your best bet might be to copy [kiosk.html.tmpl](https://raw.githubusercontent.com/poblabs/weewx-belchertown/master/skins/Belchertown/kiosk.html.tmpl) from the repo, and replace it with your current one, and see if that fixes it.

**Comment by ChrisM510** [comment]
@ThePeePs Thank you!  That worked!  Not sure what the issue was, but I frankly don't care now.  haha
