### ISSUE TITLE
29th February

### ISSUE THREAD

**Issue by roe-dl** [poblabs/weewx-belchertown#931]
**Describe the bug**

Beginning with 00:00 there are error messages in the log:

```
Feb 29 07:45:36 LokalWiki weewx[604942] ERROR weewx.reportengine: Caught unrecoverable exception in generator 'user.belchertown.HighchartsJsonGenerator'
Feb 29 07:45:36 LokalWiki weewx[604942] ERROR weewx.reportengine:         ****  day is out of range for month
Feb 29 07:45:36 LokalWiki weewx[604942] ERROR weewx.reportengine:         ****  Traceback (most recent call last):
Feb 29 07:45:36 LokalWiki weewx[604942] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 201, in run
Feb 29 07:45:36 LokalWiki weewx[604942] ERROR weewx.reportengine:         ****      obj.start()
Feb 29 07:45:36 LokalWiki weewx[604942] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 394, in start
Feb 29 07:45:36 LokalWiki weewx[604942] ERROR weewx.reportengine:         ****      self.run()
Feb 29 07:45:36 LokalWiki weewx[604942] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/user/belchertown.py", line 2536, in run
Feb 29 07:45:36 LokalWiki weewx[604942] ERROR weewx.reportengine:         ****      span_start, span_stop = archiveSpanSpan(
Feb 29 07:45:36 LokalWiki weewx[604942] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weeutil/weeutil.py", line 341, in archiveSpanSpan
Feb 29 07:45:36 LokalWiki weewx[604942] ERROR weewx.reportengine:         ****      start_dt = time_dt.replace(year=year, month=month)
Feb 29 07:45:36 LokalWiki weewx[604942] ERROR weewx.reportengine:         ****  ValueError: day is out of range for month
Feb 29 07:45:36 LokalWiki weewx[604942] ERROR weewx.reportengine:         ****  Generator terminated
```

Some JSON files in the `json` sub-directory are not cretated any more.

**Link to your website (IMPORTANT)**

https://www.woellsdorf-wetter.de

**Version of the skin you're using**

1.3b1

**To Reproduce**

It simply happens.

**Expected behavior**

JSON files will be created even for the 29th of February.

**Device Information (please complete the following information):**
 
not applicable

**Additional context**

none

**Comment by roe-dl** [comment]
According to @bellrichm in https://github.com/weewx/weewx/issues/941#issuecomment-1971401633 the option `month_delta` is deprecated, which is used within the statement that causes the error.

**Comment by roe-dl** [comment]
The next 29th of February is in 2028. So there is still plenty of time to fix the bug.

**Comment by roe-dl** [comment]
not fixed, if I know right.
