### ISSUE TITLE
I am getting errors after upgrading to weewx v5.0.1 and belchertown 1.3.1

### ISSUE THREAD

**Issue by edgararroyo** [poblabs/weewx-belchertown#942]
I changed permissions on /var/www/html to 777 and I am still gettting errors.

Here is some of syslog:

May  8 09:20:19 ubuntu weewxd[15153]: INFO weewx.manager: Added record 2024-05-08 09:20:00 EDT (1715174400) to database 'weewx.sdb'
May  8 09:20:19 ubuntu weewxd[15153]: INFO weewx.manager: Added record 2024-05-08 09:20:00 EDT (1715174400) to daily summary in 'weewx.sdb'
May  8 09:20:19 ubuntu weewxd[15153]: INFO weewx.restx: Wunderground-PWS: Published record 2024-05-08 09:20:00 EDT (1715174400)
May  8 09:20:20 ubuntu weewxd[15153]: INFO weewx.restx: PWSWeather: Published record 2024-05-08 09:20:00 EDT (1715174400)
May  8 09:20:24 ubuntu weewxd[15153]: INFO weewx.cheetahgenerator: Generated 8 files for report SeasonsReport in 4.99 seconds
May  8 09:20:26 ubuntu weewxd[15153]: INFO weewx.imagegenerator: Generated 10 images for report SeasonsReport in 1.33 seconds
May  8 09:20:26 ubuntu weewxd[15153]: INFO weewx.reportengine: Copied 5 files to /var/www/html/weewx
May  8 09:20:26 ubuntu weewxd[15153]: INFO user.belchertown: version 1.3.1
May  8 09:20:31 ubuntu weewxd[15153]: ERROR weewx.restx: StationRegistry: Failed to publish record 2024-05-08 09:20:00 EDT (1715174400): HTTP Error 429: TOO MANY REQUESTS
May  8 09:20:35 ubuntu weewxd[15153]: INFO weewx.cheetahgenerator: Generated 12 files for report Belchertown in 9.13 seconds
May  8 09:20:35 ubuntu weewxd[15153]: ERROR weewx.reportengine: Caught unrecoverable exception in generator 'weewx.reportengine.CopyGenerator'
May  8 09:20:35 ubuntu weewxd[15153]: ERROR weewx.reportengine:         ****  [Errno 1] Operation not permitted: '/var/www/html/favicon.ico'
May  8 09:20:35 ubuntu weewxd[15153]: ERROR weewx.reportengine:         ****  Traceback (most recent call last):
May  8 09:20:35 ubuntu weewxd[15153]: ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 220, in run
May  8 09:20:35 ubuntu weewxd[15153]: ERROR weewx.reportengine:         ****      obj.start()
May  8 09:20:35 ubuntu weewxd[15153]: ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 409, in start
May  8 09:20:35 ubuntu weewxd[15153]: ERROR weewx.reportengine:         ****      self.run()
May  8 09:20:35 ubuntu weewxd[15153]: ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 560, in run
May  8 09:20:35 ubuntu weewxd[15153]: ERROR weewx.reportengine:         ****      ncopy += weeutil.weeutil.deep_copy_path(path, html_dest_dir)
May  8 09:20:35 ubuntu weewxd[15153]: ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weeutil/weeutil.py", line 1811, in deep_copy_path
May  8 09:20:35 ubuntu weewxd[15153]: ERROR weewx.reportengine:         ****      shutil.copy(path, d)
May  8 09:20:35 ubuntu weewxd[15153]: ERROR weewx.reportengine:         ****    File "/usr/lib/python3.10/shutil.py", line 418, in copy
May  8 09:20:35 ubuntu weewxd[15153]: ERROR weewx.reportengine:         ****      copymode(src, dst, follow_symlinks=follow_symlinks)
May  8 09:20:35 ubuntu weewxd[15153]: ERROR weewx.reportengine:         ****    File "/usr/lib/python3.10/shutil.py", line 307, in copymode
May  8 09:20:35 ubuntu weewxd[15153]: ERROR weewx.reportengine:         ****      chmod_func(dst, stat.S_IMODE(st.st_mode))
May  8 09:20:35 ubuntu weewxd[15153]: ERROR weewx.reportengine:         ****  PermissionError: [Errno 1] Operation not permitted: '/var/www/html/favicon.ico'
May  8 09:20:35 ubuntu weewxd[15153]: ERROR weewx.reportengine:         ****  Generator terminated
May  8 09:20:35 ubuntu weewxd[15153]: Traceback (most recent call last):
May  8 09:20:35 ubuntu weewxd[15153]:   File "/usr/share/weewx/weewx/reportengine.py", line 220, in run
May  8 09:20:35 ubuntu weewxd[15153]:     obj.start()
May  8 09:20:35 ubuntu weewxd[15153]:   File "/usr/share/weewx/weewx/reportengine.py", line 409, in start
May  8 09:20:35 ubuntu weewxd[15153]:     self.run()
May  8 09:20:35 ubuntu weewxd[15153]:   File "/usr/share/weewx/weewx/reportengine.py", line 560, in run
May  8 09:20:35 ubuntu weewxd[15153]:     ncopy += weeutil.weeutil.deep_copy_path(path, html_dest_dir)
May  8 09:20:35 ubuntu weewxd[15153]:   File "/usr/share/weewx/weeutil/weeutil.py", line 1811, in deep_copy_path
May  8 09:20:35 ubuntu weewxd[15153]:     shutil.copy(path, d)
May  8 09:20:35 ubuntu weewxd[15153]:   File "/usr/lib/python3.10/shutil.py", line 418, in copy
May  8 09:20:35 ubuntu weewxd[15153]:     copymode(src, dst, follow_symlinks=follow_symlinks)
May  8 09:20:35 ubuntu weewxd[15153]:   File "/usr/lib/python3.10/shutil.py", line 307, in copymode
May  8 09:20:35 ubuntu weewxd[15153]:     chmod_func(dst, stat.S_IMODE(st.st_mode))
May  8 09:20:35 ubuntu weewxd[15153]: PermissionError: [Errno 1] Operation not permitted: '/var/www/html/favicon.ico'
May  8 09:20:40 ubuntu weewxd[15153]: INFO weewx.restx: CWOP: Published record 2024-05-08 09:20:00 EDT (1715174400)

Here is the directory listing:

ubuntu@ubuntu:/var/www/html$ ls -al
total 248
drwxrwxrwx 1 root  root     288 May  8 09:20 .
drwxrwxrwx 1 root  root       8 Mar 22  2023 ..
drwxrwxrwx 1 root  root      20 May  8 09:20 about
-rwxrwxrwx 1 root  root  128807 May  4 01:05 belchertown-dark.min.css
-rwxrwxrwx 1 root  root    3638 May  8 09:20 favicon.ico
drwxrwxrwx 1 root  root      20 May  8 09:20 graphs
drwxrwxrwx 1 root  root     858 Mar 23  2023 images
-rw-r--r-- 1 weewx weewx  32695 May  8 09:20 index.html
drwxrwxrwx 1 root  root      84 May  8 09:20 js
drwxrwxrwx 1 root  root     196 May  8 09:20 json
-rwxrwxrwx 1 root  root     810 May  8 09:10 kiosk.css
-rw-r--r-- 1 weewx weewx  22197 May  8 09:20 kiosk.html
-rw-r--r-- 1 weewx weewx    762 May  8 09:20 manifest.json
drwxrwxrwx 1 root  root     532 May  8 09:20 NOAA
drwxrwxrwx 1 root  root      20 May  8 09:20 pi
drwxrwxrwx 1 root  root      20 May  8 09:20 records
drwxrwxrwx 1 root  root      20 May  8 09:20 reports
-rwxrwxrwx 1 root  root      26 Apr 28 08:50 robots.txt
-rwxrwxrwx 1 root  root   45617 May  4 01:05 style.css
drwxrwsrwx 1 weewx weewx   1320 May  8 09:20 weewx

**Comment by edgararroyo** [comment]
Ok, got the permissions issue fixed, but it is not doing the windy iframe or the forecast...  I have the same weather station on another location and it works fine, any clues?

Windy iframe & forecast not working
https://gw3309.dns-1.net
https://gw3309.dns-1.net/weewx

Working OK
https://gw3310.dns-2.net
https://gw3310.dns-2.net/weewx
